### PR TITLE
Xadgroup/feature/membersvalidation

### PR DESCRIPTION
**Pull request by rcarpenter79**
Removed parameter checks for Members, MembersToInclude and MembersToExclude as per Issue #116.
All AppVeyor tests are passing after the changes.

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xactivedirectory/117)

### CODE REVIEW

**Comment by narrieta** [comment]
Hello, @rcarpenter79. 

I am trying to understand the motivation for this change. Would you give us a sample of #116?

Thanks!

**Comment by rcarpenter79** [comment]
Hi @narrieta 

I have uploaded a sample file containing the use case that we're using.
The aim is to keep the data and configuration separate. 
We re-use the configuration between environments but vary the data and the number of users and groups will vary.

Thanks.

[xADGroup Members Example #116.txt](https://github.com/PowerShell/xActiveDirectory/files/502909/xADGroup.Members.Example.116.txt)

**Comment by iainbrighton** [comment]
@rcarpenter79 I think I see what you're trying to do. We overcome this internally by using the equivalent of this:
```powershell
Configuration Example
{
    Import-DscResource -ModuleName ActiveDirectory

    Node ExampleDC
    {
        # Active Directory Setup here...
        
        foreach($User in $Node.Users)
        {
            xADUser $User.UserName
            {
                Ensure                          = $User.Ensure
                UserName                        = $User.UserName
                DomainName                      = $Node.DomainName
                DependsOn                       = '[xWaitForADDomain]DscForestWait'
                Password                        = (Import-Clixml -Path ('C:\Credentials\{0}.clixml' -f $User.UserName) )
                DomainAdministratorCredential   = (Import-Clixml -Path ('C:\Credentials\DomainAdmin.clixml') )
                PasswordAuthentication          = 'Negotiate'
            }
        }

        foreach($Group in $Node.Groups)
        {
            if ($null -ne $Group.Members)
            {
                xADGroup $Group.GroupName.Replace(' ', '')
                {
                    Ensure              = $Group.Present
                    GroupName           = $Group.GroupName
                    Description         = $Group.Description
                    Members             = $Group.Members
                    GroupScope          = $Group.GroupScope
                    Path		        = $Group.Path
                    Notes		        = $Group.Notes
                    Credential	        = (Import-Clixml -Path 'C:\Credentials\DomainAdmin.clixml')
                    DependsOn           = $Group.DependsOn
                }
            }
            else
            {
                xADGroup $Group.GroupName.Replace(' ', '')
                {
                    Ensure              = $Group.Present
                    GroupName           = $Group.GroupName
                    Description         = $Group.Description
                    MembersToInclude    = $Group.MembersToInclude
                    MembersToExclude    = $Group.MembersToExclude
                    GroupScope          = $Group.GroupScope
                    Path		        = $Group.Path
                    Notes		        = $Group.Notes
                    Credential	        = (Import-Clixml -Path 'C:\Credentials\DomainAdmin.clixml')
                    DependsOn           = $Group.DependsOn
                }
            }
        }
    }
}
```
@narrieta Wouldn't it be handy to be able to use splatting against DSC resources inside of configurations? We use this "work around" all the time, but it does make for a lot of extra unnecessary code.

**Comment by rcarpenter79** [comment]
@iainbrighton I considered your example first. The problem I saw with this is the resource configuration in the else block is only valid when MembersToInclude and MembersToExclude aren't empty. There are three other permutations that could be specified in the data file when either or both are empty.

Splatting would be great though.

**Comment by eshaparmar** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xactivedirectory/117)*

**Pull request merged**
