### PR TITLE
xADUser: Add ChangePasswordAtLogon Parameter

### LINKED ISSUE #246: xADUser: Unable to add ChangePasswordAtLogon to the New-ADUser cmdlet
Hi guys I am trying to add the ChangePasswordAtLogon Parameter to the new-aduser so everytime a new users gets created they have to reset the password at first logon. do you know why I can't just simply replace New-ADUser @newADUserParams -SamAccountName $UserName;  to  New-ADUser @newADUserParams -SamAccountName $UserName -ChangePasswordAtLogon $true -Verbose; or is there any other way I can change add the ChangePasswordAtLogon value so it only became available when a new users get created and does not touch any of the existing users.

### PR DESCRIPTION
**Pull request by X-Guardian**
#### Pull Request (PR) description

This PR adds the `ChangePasswordAtLogon` parameter to the xADUser Resource.

It also adds an error exception to check whether the `ChangePasswordAtLogon` and `PasswordNeverExpires` properties have both been set to `true`, which is invalid.

#### This Pull Request (PR) fixes the following issues

- Fixes #246 

#### This Pull Request (PR) partly fixes the following issues

- #44

#### Task list

- [x] Added an entry under the Unreleased section in the CHANGELOG.md.
      Entry should say what was changed, and how that affects users (if applicable).
- [ ] Resource documentation added/updated in README.md.
- [x] Resource parameter descriptions added/updated in README.md, schema.mof
      and comment-based help.
- [ ] Comment-based help added/updated.
- [x] Localization strings added/updated in all localization files as appropriate.
- [ ] Examples appropriately added/updated.
- [x] Unit tests added/updated. See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [ ] Integration tests added/updated (where possible). See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [x] New/changed code adheres to [DSC Resource Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md) and [Best Practices](https://github.com/PowerShell/DscResources/blob/master/BestPractices.md).

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xactivedirectory/371)

### CODE REVIEW

**Comment by johlju** [comment]
@X-Guardian thank you for closing all these issue! 😃 🙇 Merging this as soon as the tests passes again (pushed the latest changes from dev).

**Comment by X-Guardian** [comment]
No problem @johlju. I need this for the current project I'm working on.

Looking at the code in the `xADUser` resource, there are issues with it processing parameters that are set to null or an empty string. (A common problem in DSC resources from what I've seen). I'll create an issue for this and raise a pull request to fix it.
I'm also generalising the code that was added to support the `ServicePrincipalNames` array property so that it can be used for easily adding other array properties, such as `ProxyAddresses` which would be useful, and is requested in #254.

Is there any official release schedule for DSC modules or is it ad hoc?

**Comment by X-Guardian** [comment]
@johlju, I've discovered an issue with this PR. I've missed adding `ADProperty = 'pwdLastSet'` to the `ChangePasswordAtLogon` property of the `adPropertyMap`.

What's the process in this circumstance? I've restored my branch and pushed the update. Can you revert the Merge?

**Comment by johlju** [comment]
Ah, good catch! Easiest is to rebase against dev, then send in a new PR that adds this. You can just create a new branch to with that change. 🙂 

It's more work reverting the PR, and in the end I think you need to send in a new PR anyway, let us only revert commits in dev when and if the entire PR must be reverted. 🙂

**Comment by johlju** [comment]
@X-Guardian Sorry, missed answering questions here

> Looking at the code in the xADUser resource, there are issues with it processing parameters that are set to null or an empty string. (A common problem in DSC resources from what I've seen). I'll create an issue for this and raise a pull request to fix it.

Would this be solved (or helped to be solved) by using the helper function [`Compare-ResourcePropertyState`](https://github.com/PowerShell/xActiveDirectory/blob/dev/Modules/xActiveDirectory.Common/xActiveDirectory.Common.psm1#L1554) and the pattern added to the resource xADObjectEnabledState

https://github.com/PowerShell/xActiveDirectory/blob/f26ddf5e4aa1b92453507c27ec8a225b6d0b54b0/DSCResources/MSFT_xADObjectEnabledState/MSFT_xADObjectEnabledState.psm1#L184

https://github.com/PowerShell/xActiveDirectory/blob/f26ddf5e4aa1b92453507c27ec8a225b6d0b54b0/DSCResources/MSFT_xADObjectEnabledState/MSFT_xADObjectEnabledState.psm1#L329

> Is there any official release schedule for DSC modules or is it ad hoc?

Normally one week after each DSC Community Call which is ~6 weeks apart (next call is scheduled for June 19:th). You can add it to your calendar by downloading the zip (ICS) file here https://github.com/PowerShell/DscResources/tree/master/CommunityCalls.

**Pull request merged**
