### PR TITLE
xADReplicationSiteLink (Fixes #191) 

### LINKED ISSUE #148: New resource for xActiveDirectory: xADSiteLink
I'd like to contribute a new resource to this module:

- xADSiteLink - creates and manages Active Directory site links

Opening an issue before forking as per the contribution guidelines.

(Edited to split resources into seperate issues as requested below)

### LINKED ISSUE #191: Should there be xADReplicationSiteLink Resource?
Hi folks. This may be due to my own ignorance, but as I was browsing the module I didn't see any resource for manage AD Site Links. And I didn't see any reference in the code or issues elsewhere about it so I thought I'd post something so it's at least out here for other curious people like me.

Is there a reason why there does not currently exist an xADReplicationSiteLink resource? Perhaps some technical limitation in AD that prevented this from being effectively managed from PowerShell DSC?

Any insight is appreciated. :) If this is something people maybe wanted I could perhaps work on a PR with a new resource for this. :) Thanks!

### PR DESCRIPTION
**Pull request by anLopCodez**
#### Pull Request (PR) description

Added the xADReplicationSiteLink resource which adds the ability to manage AD replication sites via DSC. 

#### This Pull Request (PR) fixes the following issues

- Fixes #191 
- Fixes #148 

#### Task list

- [x] Added an entry under the Unreleased section of the change log in the README.md.
      Entry should say what was changed, and how that affects users (if applicable).
- [x] Resource documentation added/updated in README.md.
- [x] Resource parameter descriptions added/updated in README.md, schema.mof
      and comment-based help.
- [x] Comment-based help added/updated.
- [x] Localization strings added/updated in all localization files as appropriate.
- [x] Examples appropriately added/updated.
- [x] Unit tests added/updated. See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [x] Integration tests added/updated (where possible). See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [x] New/changed code adheres to [DSC Resource Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md) and [Best Practices](https://github.com/PowerShell/DscResources/blob/master/BestPractices.md).

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xactivedirectory/232)

### CODE REVIEW

**Comment by anLopCodez** [comment]
@johlju Were the code changes sufficient or is there anything else that needs to be modified? :)

**Comment by anLopCodez** [comment]
@johlju all the comments have been updated. Any chance you can give this a glance? Thanks!

**Comment by anLopCodez** [comment]
Is this ever going to get merged in? Lol

**Comment by johlju** [comment]
@anLopCodez There is no community maintainer of this module, so that is why it take longer,m and there are unfortunately few in the community that review PR's, those that do has a lot of PR's to review in other repositories (during there free time). I would be awesome to get more folks in the community to review PR's, then it will be much faster to get them merged. 

Personally I had a lot of work at the day job, so haven't have much free time the last four months. But reviewing this one again now. 🙂

**Comment by anLopCodez** [comment]
@johju any chance to take a look at the updates? Thanks :)

**Comment by johlju** [comment]
@anLopCodez Sorry! I missed that you fixed my last comments. 😕 I will review this one tomorrow! 🙂

**Pull request merged**
