### PR TITLE
updated tests to not be dependent on git - also delete DSCResource.Tests file.... was there a reason this was in here?

### PR DESCRIPTION
**Pull request by mbreakey3**
This change is [Reviewable](https://reviewable.io/reviews/powershell/xactivedirectory/89)

### CODE REVIEW

**Comment by TravisEz13** [comment]
:lgtm: I'll leave open for review for some time for contributors to comment.

---

Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xactivedirectory/89#-:-KFr3bUJwdNyKTXQ5sWV:-1741037000)*

**Comment by PlagueHO** [comment]
Can you add the test template version number in here as well? Hope I'm not being a pain :smile:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xactivedirectory/89#-:-KFr5fWLhSrroj0EV8T4:-814481873)*

**Comment by TravisEz13** [comment]
@mbreakey3 Can you respond to @plagueho ?

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xactivedirectory/89#-:-KFr79YN56yhVOUxTBwd:789868413)*

**Comment by mbreakey3** [comment]
@PlagueHO Yeah, where is the version kept in this module?

**Comment by PlagueHO** [comment]
@mbreakey3 - Apologies, for the unit/integration test template version number it goes in the header (the same place as in the master test templates).

- Unit tests (see https://github.com/PowerShell/DscResources/blob/master/Tests.Template/unit_template.ps1):
```powershell
...
#region HEADER
# Unit Test Template Version: 1.1.0
...
```

- Integration tests (https://github.com/PowerShell/DscResources/blob/master/Tests.Template/integration_template.ps1):
```powershell
...
#region HEADER
# Unit Test Template Version: 1.1.0
...
```
See the section "Updating Resource DSC Resource Tests" in https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md

Does that make more sense?

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xactivedirectory/89#-:-KFuLGas2SZk5Hc-QNkw:-1732218086)*

**Comment by mbreakey3** [comment]
@PlagueHO Yes, thank you! We're currently brainstorming possible alternatives to this solution, so I'm going to wait to make any more changes until that's resolved (hopefully by today), if we stick with this though, I'll be sure to update the versions on all the tests

**Comment by PlagueHO** [comment]
@mbreakey3 - sweet! I'll leave it with you lot - let me know if you need me to do anything :smile:

**Pull request merged**
