### PR TITLE
xADObjectPermissionEntry: Using more generic "AD:" to prevent errors

### LINKED ISSUE #236: xADObjectPermissionEntry: Cannot find a provider with the name 'Microsoft.ActiveDirectory.Management\ActiveDirectory'
#### Details of the scenario you tried and the problem that is occurring
Trying to set the replicating changes permission for a user account I get the error message "Cannot find a provider with the name 'Microsoft.ActiveDirectory.Management\ActiveDirectory'" in DSC log.
Maybe a missing Windows Feature? Some dependency? @claudiospizzi since you created the resource in #186 maybe you have some input? 

#### Verbose logs showing the problem
```
{"time": "2018-12-28T12:30:04.924+01:00", "type": "verbose", "message": "[DEV-SP2019]: LCM:  [ Start  Resource ]  [[xADObjectPermissionEntry]ReplicateDirectoryChangesPermission]  "},
  {"time": "2018-12-28T12:30:04.924+01:00", "type": "verbose", "message": "[DEV-SP2019]: LCM:  [ Start  Test     ]  [[xADObjectPermissionEntry]ReplicateDirectoryChangesPermission]  "},
  {"time": "2018-12-28T12:30:05.737+01:00", "type": "error", "message": "Cannot find a provider with the name 'Microsoft.ActiveDirectory.Management\\ActiveDirectory'."},
  {"time": "2018-12-28T12:30:05.752+01:00", "type": "verbose", "message": "[DEV-SP2019]: LCM:  [ End    Test     ]  [[xADObjectPermissionEntry]ReplicateDirectoryChangesPermission]  in 0.8290 seconds."},
  {"time": "2018-12-28T12:30:05.752+01:00", "type": "error", "message": "The PowerShell DSC resource '[xADObjectPermissionEntry]ReplicateDirectoryChangesPermission' with SourceInfo 'C:\\SharePoint-DSC\\config\\SPDevConfig.DSC.ps1::65::2::xADObjectPermissionEntry' threw one or more non-terminating errors while running the Test-TargetResource functionality. These errors are logged to the ETW channel called Microsoft-Windows-DSC/Operational. Refer to this channel for more details."},
```

#### Suggested solution to the issue
I looked into the resource MSFT_xADObjectPermissionEntry.psm1 in line 76 it does this (and 191 & 232 respectively):
` $acl = Get-Acl -Path "Microsoft.ActiveDirectory.Management\ActiveDirectory:://RootDSE/$Path"`

This doesn't work on my machine. When I do the following: 
```
Get-Acl -Path "AD:CN=sp_sync,OU=ServiceAccounts,DC=spdev,DC=test"
#I get this the following path
Path   : Microsoft.ActiveDirectory.Management.dll\ActiveDirectory:://RootDSE/CN=sp_sync,OU=ServiceAccounts,DC=spdev,DC=
         test
```
It looks like the '`.dll`' is missing from the path. I don't understand why `AD:` isn't used anyways? Why the complication with RootDSE etc.?

I changed line 76 (and 191/232 respectively) to read:  
`$acl = Get-Acl -Path "Microsoft.ActiveDirectory.Management.dll\ActiveDirectory:://RootDSE/$Path"`
and everything is working now. I don't want to issue a pull request because I am not sure about the implications.

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell
	xADObjectPermissionEntry ReplicateDirectoryChangesPermission
    {
      Path                               = "DC=spdev,DC=test"
      IdentityReference                  = "SPDEV\sp_sync"
      ActiveDirectoryRights              = "ExtendedRight"
      AccessControlType                  = "Allow"
      ObjectType                         = "1131f6aa-9c07-11d1-f79f-00c04fc2dcd2" # Replicate Directory Changes Permission
      ActiveDirectorySecurityInheritance = "All"
      InheritedObjectType                = "00000000-0000-0000-0000-000000000000"
      Ensure                             = "Present"
    }
```

#### The operating system the target node is running
OsName               : Microsoft Windows Server 2019 Datacenter
OsOperatingSystemSKU : DatacenterServerEdition
OsArchitecture       : 64-bit
WindowsVersion       : 1809
WindowsBuildLabEx    : 17763.1.amd64fre.rs5_release.180914-1434
OsLanguage           : en-US
OsMuiLanguages       : {en-US}

#### Version and build of PowerShell the target node is running
PSVersion                      5.1.17763.134
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17763.134
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

#### Version of the DSC module that was used ('dev' if using current dev branch)
2.22.0.0

### PR DESCRIPTION
**Pull request by DennisGaida**
As described in https://github.com/PowerShell/xActiveDirectory/issues/236

#### Pull Request (PR) description
Using `AD:` is more generic than the currently used `Microsoft.ActiveDirectory.Management\ActiveDirectory:://RootDSE/$Path` which doesn't work on all machines (sometimes a `.dll` is added). Using `AD:` instead solves this problem.

#### This Pull Request (PR) fixes the following issues
- Fixes #236

#### Task list

- [ ] Added an entry under the Unreleased section of the change log in the README.md.
      Entry should say what was changed, and how that affects users (if applicable).
- [ ] Resource documentation added/updated in README.md.
- [ ] Resource parameter descriptions added/updated in README.md, schema.mof
      and comment-based help.
- [ ] Comment-based help added/updated.
- [ ] Localization strings added/updated in all localization files as appropriate.
- [ ] Examples appropriately added/updated.
- [ ] Unit tests added/updated. See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [ ] Integration tests added/updated (where possible). See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [ ] New/changed code adheres to [DSC Resource Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md) and [Best Practices](https://github.com/PowerShell/DscResources/blob/master/BestPractices.md).

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xactivedirectory/243)

### CODE REVIEW

**Comment by brwilkinson** [comment]
@DennisGaida looks good, are you okay to rebase and update?

**Comment by DennisGaida** [comment]
I updated the PR with the latest changes from the dev branch

**Comment by johlju** [comment]
I just merged a PR that fixes the problem with the tests failing. Please rebase this PR again.

**Comment by johlju** [comment]
@DennisGaida Thanks for this!

**Pull request merged**
