### PR TITLE
xActiveDirectory: Opt-in to "Common Tests - Validate example files"

### LINKED ISSUE #279: xActiveDirectory: Enable the tests "Common Tests - Validate Example Files"
To help contributors and maintainers we should enable the common test "Common Tests - Validate Example Files".

### PR DESCRIPTION
**Pull request by X-Guardian**
#### Pull Request (PR) description

This PR opts-in to the "Common Tests - Validate example files" DSC Resource tests.

Summary of changes:

- Add "Common Tests - Validate Example Files" to `.MetaTestOptIn.json`
- Standardise test configuration naming to allow tests to run on the following resources:
  - xADDomain
  - xADDomainController
  - xADDomainDefaultPasswordPolicy
  - xADDomainTrust
  - xADForestProperties
  - xADGroup
  - xADKDSKey
  - xADManagedServiceAccount
  - xADObjectPermissionEntry
  - xADOrganizationalUnit
  - xADRecycleBin
  - xADReplicationSite
  - xADReplicationSiteLink
  - xADUser
- Standardise naming of ConfigurationData variable to allow tests to run on the following resources:
  - XADDomain
- Fix incorrect parameter names and values in the following resources:
  - xADForestProperties (OutputPath)
  - xADKDSKey (AllowUnsafeEffectiveTime)
- Remove incorrect comma in xADDomainDefaultPasswordPolicy parameter list
- Remove PSDscAllowPlainTextPassword to allows tests to run on the following resources:
  - xADDomain
- Remove unnecessary `TrustDirection` parameter and configuration data from `xADDomainTrust` `NewOneWayTrust` example
- Format all documents for layout consistency

#### This Pull Request (PR) fixes the following issues

- Fixes #279

#### Task list

- [ ] Added an entry under the Unreleased section in the CHANGELOG.md.
      Entry should say what was changed, and how that affects users (if applicable).
- [ ] Resource documentation added/updated in README.md.
- [ ] Resource parameter descriptions added/updated in README.md, schema.mof
      and comment-based help.
- [ ] Comment-based help added/updated.
- [ ] Localization strings added/updated in all localization files as appropriate.
- [x] Examples appropriately added/updated.
- [ ] Unit tests added/updated. See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [ ] Integration tests added/updated (where possible). See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [ ] New/changed code adheres to [DSC Resource Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md) and [Best Practices](https://github.com/PowerShell/DscResources/blob/master/BestPractices.md).

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xactivedirectory/309)

### CODE REVIEW

**Comment by X-Guardian** [comment]
OK, how about we remove the "Common Tests - Validate Example Files To Be Published" from this PR then, get this merged, then I'll create another PR with all the changes needed for the publishing?

**Comment by johlju** [comment]
@X-Guardian that works for me.

**Comment by johlju** [comment]
Just need a rebase and I merge this one.

**Comment by X-Guardian** [comment]
@johlju, can you resolve these conflicts online for me? I just get a spinning logo when I try. Otherwise it will have to wait till I get home this evening.

**Comment by johlju** [comment]
@X-Guardian I rebased the PR.

**Pull request merged**
