### PR TITLE
xADKDSKey: Create new DSC Resource: xADKDSKey

### PR DESCRIPTION
**Pull request by kungfu71186**
Renamed to proper naming standard and add most test cases

Finished test cases

Fixed styling issues and add README

updated readme

#### Pull Request (PR) description
Helps manage KDS Root keys in Active Directory

#### This Pull Request (PR) fixes the following issues
Closes https://github.com/PowerShell/xActiveDirectory/pull/165

#### Task list

- [x] Added an entry under the Unreleased section of the change log in the README.md.
      Entry should say what was changed, and how that affects users (if applicable).
- [x] Resource documentation added/updated in README.md.
- [x] Resource parameter descriptions added/updated in README.md, schema.mof
      and comment-based help.
- [x] Comment-based help added/updated.
- [x] Localization strings added/updated in all localization files as appropriate.
- [x] Examples appropriately added/updated.
- [x] Unit tests added/updated. See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [x] Integration tests added/updated (where possible). See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [x] New/changed code adheres to [DSC Resource Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md) and [Best Practices](https://github.com/PowerShell/DscResources/blob/master/BestPractices.md).

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xactivedirectory/256)

### CODE REVIEW

**Comment by kungfu71186** [comment]
@johlju I think this is ready for initial review. I still haven't reviewed it myself or done one last integration test, but should be good enough for a first look.

**Comment by kungfu71186** [comment]
Cleaned up the code quite a bit, made quite a few changes. It should be good for another review if you have with the exception of the test cases. I haven't really touched those too much, so you can skip over those for now. I may not be able to get back to this for a little bit.

Still need to:

- [ ] Create additional test cases for new functions

- [ ] Fix the localization messages

- [ ] Update README with additional information

**Comment by johlju** [comment]
Merged the localization helper functions.

**Comment by johlju** [comment]
@kungfu71186 Impressive work on this one! It looks close to be ready for merge! 🙂

**Comment by johlju** [comment]
@kungfu71186 This looking good to me. You may fix additional stuff in another PR? I couldn't help you resolve the conflicts in this one, since we need to move the change log entry to the CHANGELOG.md. Can you resolve the conflicts in this one, and I will merge once the test passes again! 🙂

**Comment by kungfu71186** [comment]
@johlju yeah, I'll take care of the conflicts. What else was outstanding?

**Comment by johlju** [comment]
Nothing outstanding. You had thoughts of improving the tests, but that can be another PR. If the tests passed now I will merge. :)

**Comment by kungfu71186** [comment]
Oh yeah. That will be for MSA and this one. Now that I know you can do nested context. But yeah, as of now the tests are fine, probably not the cleanest though :)

**Comment by johlju** [comment]
> Oh yeah. That will be for MSA and this one. Now that I know you can do nested context. But yeah, as of now the tests are fine, probably not the cleanest though :)

You did an awesome job on them! If the work, then its good enough. :små

**Comment by johlju** [comment]
Ah, sorry closed by mistake. Not sure what key combination I pressed to do that. :/

**Pull request merged**
