### PR TITLE
Added DomainMode and ForestMode parameters

### PR DESCRIPTION
**Pull request by corydwood**

### CODE REVIEW

**Comment by iainbrighton** [comment]
DOH! As previously mentioned I've started work on a rewrite of this resource. I'll try and pull these changes in, but it'll probably be messy :/

I'd also like to implement the 2008 R2 dcpromo functionality you mentioned. Do you want me to put that in or wait until the outstanding PR gets merged and implement it yourself?

**Comment by corydwood** [comment]
If you're already working on adding the dcpromo functionality as well, you can just add that in. If not, I can add it after the outstanding PR is merged.

**Comment by TravisEz13** [comment]
@iainbrighton  @corydwood Can you let me know where this change will be taken?

There are no unit tests here.
No summary of changes in the readme.md

**Comment by iainbrighton** [comment]
I'll try and pull this patch into the xADDomain PR and add test coverage there. This should test my Git-foo! ;)

**Comment by TravisEz13** [comment]
@corydwood Can I close this PR?

**Comment by corydwood** [comment]
@TravisEz13 Sure.

**Pull request closed without merging**
