### PR TITLE
xADUser: Add Additional Parameters

### PR DESCRIPTION
**Pull request by X-Guardian**
#### Pull Request (PR) description

This PR adds the following parameters to the `xADUser` resource:

- AccountNotDelegated
- AllowReversiblePasswordEncryption
- CompoundIdentitySupported
- PasswordNotRequired
- SmartcardLogonRequired
- LogonWorkstations
- Organization
- OtherName

These are all the remaining `String` and `Boolean` parameters available in the `New/Get/Set-ADUser` PowerShell cmdlets.

#### This Pull Request (PR) partly fixes the following issues

None

#### Task list

- [x] Added an entry under the Unreleased section in the CHANGELOG.md.
      Entry should say what was changed, and how that affects users (if applicable).
- [ ] Resource documentation added/updated in README.md.
- [x] Resource parameter descriptions added/updated in README.md, schema.mof
      and comment-based help.
- [x] Comment-based help added/updated.
- [ ] Localization strings added/updated in all localization files as appropriate.
- [ ] Examples appropriately added/updated.
- [x] Unit tests added/updated. See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [ ] Integration tests added/updated (where possible). See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [x] New/changed code adheres to [DSC Resource Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md) and [Best Practices](https://github.com/PowerShell/DscResources/blob/master/BestPractices.md).

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xactivedirectory/373)

### CODE REVIEW

**Comment by johlju** [comment]
@X-Guardian Can you please look at rebasing this, you got a lot of files that has already been merged (see for example commit ec1f69e).

**Comment by X-Guardian** [comment]
Done. (forgot to force push)

**Comment by X-Guardian** [comment]
Did you see my message on #371. Shall we get that sorted first?

**Comment by johlju** [comment]
Yes I saw that comment after I reviewed this PR (lot of community e-mails in the backlog :) )
It does not matter what order we merge, merge this or merge a new PR that fixes the issue in #371. 
Work on the one you want to merge first :)

**Comment by johlju** [comment]
Merged the other one, and I added latest changes to this PR.

**Comment by X-Guardian** [comment]
This one could do with another test. Hang fire on merging till I add it.

**Comment by johlju** [comment]
@X-Guardian ah, then make sure to rebase in latest changes to your PR and force push so this matches your local branch (since I asked GitHub GUI to merge in dev-branch).

**Pull request merged**
