### PR TITLE
New resource xADForestProperties (Fixes #177)

### LINKED ISSUE #177: xActiveDirectory: new resource for UPN and SPN suffix management
I'd like to recommend adding a new resource to manage User Name Principal (UPN) and Service Principal Name (SPN) suffix properties in a forest.  This resource can be called xADPrincipalNameSuffix.  I have a current need for this, so I've started working on it in a fork.

### PR DESCRIPTION
**Pull request by regedit32**
Created a new resource to handle managing UPN and SPN suffixes in a Forest similar to this manual process [Add User Principal Name Suffixes](https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2008-R2-and-2008/cc772007(v=ws.11)).  Opened issue #177 for this proposed resource.

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xactivedirectory/178)

### CODE REVIEW

**Comment by johlju** [comment]
Reviewed 3 of 5 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 37 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/powershell/xactivedirectory/178#-L3sDmC4iKGRJgeIZFNA:-L3sDmC4iKGRJgeIZFNB:b-9h1bdn) (no related file):*
Could you please add `Fixes #177` to the PR description, or PR title, so that the issue auto-closes on merge.

---

*[README.md, line 257 at r2](https://reviewable.io:443/reviews/powershell/xactivedirectory/178#-L3sDY4BcWkWjs4hIwl2:-L3sDY4BcWkWjs4hIwl3:b-7fu0rz) ([raw file](https://github.com/powershell/xactivedirectory/blob/f7836cbdd2511296263ecaf03135f3ef5d089260/README.md#L257)):*
> xADPrincipalNameSuffix

Discussion about the name in the resource is ongoing in the issue #177. Depending on name change the resource description might need to change a little.

---

*[README.md, line 261 at r2](https://reviewable.io:443/reviews/powershell/xactivedirectory/178#-L3sEs7Nwudp2E9mKOdd:-L3sEs7Nwudp2E9mKOde:biyxe21) ([raw file](https://github.com/powershell/xactivedirectory/blob/f7836cbdd2511296263ecaf03135f3ef5d089260/README.md#L261)):*
> ```Markdown
> The xADPrincipalNameSuffix DSC resource will manage User Principal Name (UPN) suffixes and Service Principal Name suffixes in a forest.
> 
> * **ForestName**: Specifies the target Active Directory forest for the change
> ```

We should add '.' at the end of the sentence here. 

---

*[README.md, line 262 at r2](https://reviewable.io:443/reviews/powershell/xactivedirectory/178#-L3sEPpyKhV0SUqD0rlZ:-L3sEPpyKhV0SUqD0rl_:b-q1l19a) ([raw file](https://github.com/powershell/xactivedirectory/blob/f7836cbdd2511296263ecaf03135f3ef5d089260/README.md#L262)):*
> Specifies the User Principal Name (UPN)

Maybe we could change this to 'Specifies one or more User...' since it is an array.

---

*[README.md, line 262 at r2](https://reviewable.io:443/reviews/powershell/xactivedirectory/178#-L3sF1uTfoTCm16WFz3t:-L3sF1uTfoTCm16WFz3u:bfv44v6) ([raw file](https://github.com/powershell/xactivedirectory/blob/f7836cbdd2511296263ecaf03135f3ef5d089260/README.md#L262)):*
> ```Markdown
> 
> * **ForestName**: Specifies the target Active Directory forest for the change
> * **UserPrincipalNameSuffix**: Specifies the User Principal Name (UPN) Suffix to add/remove. (optional)
> ```

Nitpick (non-blocking): Could we have `(optional)` before the '.', or at the start of the sentence? Or is it more correct to write it this way?

---

*[README.md, line 263 at r2](https://reviewable.io:443/reviews/powershell/xactivedirectory/178#-L3sEbJL5vfjUZu3i2JV:-L3sEbJL5vfjUZu3i2JW:b-oc7vhk) ([raw file](https://github.com/powershell/xactivedirectory/blob/f7836cbdd2511296263ecaf03135f3ef5d089260/README.md#L263)):*
> Specifies the Service Principal Name (SPN)

Maybe we could change this to 'Specifies one or more Service...' since it is an array.

---

*[README.md, line 264 at r2](https://reviewable.io:443/reviews/powershell/xactivedirectory/178#-L3sFoTeFpA1n_y6ZYQr:-L3sFoTeFpA1n_y6ZYQs:b-k1gysm) ([raw file](https://github.com/powershell/xactivedirectory/blob/f7836cbdd2511296263ecaf03135f3ef5d089260/README.md#L264)):*
> "Specifies

Seems a double-quote sneaked in here at the beginning or the sentence. 

---

*[README.md, line 1205 at r2](https://reviewable.io:443/reviews/powershell/xactivedirectory/178#-L3sHIBrY7OI6lG2qs-I:-L3sHIBrY7OI6lG2qs-J:b-uz7eay) ([raw file](https://github.com/powershell/xactivedirectory/blob/f7836cbdd2511296263ecaf03135f3ef5d089260/README.md#L1205)):*
> ```Markdown
> ### Create User Principal Name (UPN) suffixes and Service Principal Name suffixes
> 
> In this example, we create a 'NANO-200' computer account in the 'Nano' OU of the 'example.com' Active Directory domain as well as creating an Offline Domain Join Request file.
> ```

I think this description is not correct of what the example actually does?

---

*[README.md, line 1243 at r2](https://reviewable.io:443/reviews/powershell/xactivedirectory/178#-L3sHb3ZEOygA85UpNAu:-L3sHb3ZEOygA85UpNAv:b-qkr4br) ([raw file](https://github.com/powershell/xactivedirectory/blob/f7836cbdd2511296263ecaf03135f3ef5d089260/README.md#L1243)):*
> $params

Could we change this to `$parameters` to avoid abbreviations?

---

*[README.md, line 1244 at r2](https://reviewable.io:443/reviews/powershell/xactivedirectory/178#-L3sHVA0knR5wpzSQMPW:-L3sHVA0knR5wpzSQMPX:brrru23) ([raw file](https://github.com/powershell/xactivedirectory/blob/f7836cbdd2511296263ecaf03135f3ef5d089260/README.md#L1244)):*
> "dc.contoso.com"

Could we use single-quotes here instead, to be consistent? Throughout.

We try to avoid using double-quotes where it's not needed (in HQRM). There is not actual guideline for this apparently so I leave this non-blocking.

---

*[DSCResources/MSFT_xADPrincipalNameSuffix/MSFT_xADPrincipalNameSuffix.psm1, line 22 at r2](https://reviewable.io:443/reviews/powershell/xactivedirectory/178#-L3sIwM4PK3RUl2nfFoK:-L3sIwM4PK3RUl2nfFoL:b-twr2mg) ([raw file](https://github.com/powershell/xactivedirectory/blob/f7836cbdd2511296263ecaf03135f3ef5d089260/DSCResources/MSFT_xADPrincipalNameSuffix/MSFT_xADPrincipalNameSuffix.psm1#L22)):*
> ```PowerShell
> . $adCommonFunctions
> 
> function Get-TargetResource
> ```

Could you please add comment-based help? Throughout.

---

*[DSCResources/MSFT_xADPrincipalNameSuffix/MSFT_xADPrincipalNameSuffix.psm1, line 45 at r2](https://reviewable.io:443/reviews/powershell/xactivedirectory/178#-L3sIehat8SJjSEeaPoO:-L3sIehat8SJjSEeaPoP:b-u6jasa) ([raw file](https://github.com/powershell/xactivedirectory/blob/f7836cbdd2511296263ecaf03135f3ef5d089260/DSCResources/MSFT_xADPrincipalNameSuffix/MSFT_xADPrincipalNameSuffix.psm1#L45)):*
> ```PowerShell
> 
>         [Parameter()]
>         [ValidateSet("Present","Absent")]
> ```

Could we use single-quotes here instead, to be consistent? Throughout.

We try to avoid using double-quotes where it's not needed (in HQRM). There is not actual guideline for this apparently so I leave this non-blocking.

---

*[DSCResources/MSFT_xADPrincipalNameSuffix/MSFT_xADPrincipalNameSuffix.psm1, line 61 at r2](https://reviewable.io:443/reviews/powershell/xactivedirectory/178#-L3sJcgWVrwfZP1o7G4T:-L3sJcgWVrwfZP1o7G4U:b-psalk6) ([raw file](https://github.com/powershell/xactivedirectory/blob/f7836cbdd2511296263ecaf03135f3ef5d089260/DSCResources/MSFT_xADPrincipalNameSuffix/MSFT_xADPrincipalNameSuffix.psm1#L61)):*
> ```PowerShell
>         ServicePrincipalNameSuffix = @($forest.SPNSuffixes)
>         Credential = ""
>         Ensure = $Ensure
> ```

This will return the state as 'Present' or 'Absent' even if it isn't. Could we evaluate if the values are actually in desired state and return the actual state? 

---

*[DSCResources/MSFT_xADPrincipalNameSuffix/MSFT_xADPrincipalNameSuffix.psm1, line 101 at r2](https://reviewable.io:443/reviews/powershell/xactivedirectory/178#-L3sLnoEyf3lPNG7BDht:-L3sLnoEyf3lPNG7BDhu:bymbmq8) ([raw file](https://github.com/powershell/xactivedirectory/blob/f7836cbdd2511296263ecaf03135f3ef5d089260/DSCResources/MSFT_xADPrincipalNameSuffix/MSFT_xADPrincipalNameSuffix.psm1#L101)):*
> if(

We should use a space between keyword and parenthesis; `if (`. Throughout.

https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md#one-space-between-keyword-and-parenthesis

---

*[DSCResources/MSFT_xADPrincipalNameSuffix/MSFT_xADPrincipalNameSuffix.psm1, line 105 at r2](https://reviewable.io:443/reviews/powershell/xactivedirectory/178#-L3sObwmtUT5Zrxzmlp8:-L3sObwmtUT5Zrxzmlp9:b-uaii1w) ([raw file](https://github.com/powershell/xactivedirectory/blob/f7836cbdd2511296263ecaf03135f3ef5d089260/DSCResources/MSFT_xADPrincipalNameSuffix/MSFT_xADPrincipalNameSuffix.psm1#L105)):*
> ```PowerShell
>         if($Ensure -eq 'Present')
>         {
>             $compare = Compare-Object -ReferenceObject $UserPrincipalNameSuffix -DifferenceObject $forest.UPNSuffixes
> ```

Can we have a logical error here :thinking:

What happens in this scenario.
1. If the user want's to add UPN 'a' and there are no UPN's yet, LCM will run and this will correctly be false (different). 
1. Next time LCM runs, the user still wants want's to add UPN 'a' and now there is a UPN 'a' already, this will correctly be $true (same). 
1. Another user manually adds UPN 'b' to the forest.
1. LCM runs and user still wants want's to add only UPN 'a', and now there is a UPN 'a' and 'b' - won't this wrongly be false (different) and will set `$inDesiredState = $false` and try to run `Set-TargetResource`?

Same for SPN below.

---

*[DSCResources/MSFT_xADPrincipalNameSuffix/MSFT_xADPrincipalNameSuffix.psm1, line 141 at r2](https://reviewable.io:443/reviews/powershell/xactivedirectory/178#-L3sN19v3hUGMRsh5ArE:-L3sN19v3hUGMRsh5ArF:bbt6ish) ([raw file](https://github.com/powershell/xactivedirectory/blob/f7836cbdd2511296263ecaf03135f3ef5d089260/DSCResources/MSFT_xADPrincipalNameSuffix/MSFT_xADPrincipalNameSuffix.psm1#L141)):*
> ForestSPNSuffixNotInDesiredState

Should be `ForestSpnSuffixNotInDesiredState` (Pascal Case), the same as it is in the strings-file already.

---

*[DSCResources/MSFT_xADPrincipalNameSuffix/MSFT_xADPrincipalNameSuffix.psm1, line 152 at r2](https://reviewable.io:443/reviews/powershell/xactivedirectory/178#-L3sMZhuskZVBgd4PgO4:-L3sMZhuskZVBgd4PgO5:b-plqqrj) ([raw file](https://github.com/powershell/xactivedirectory/blob/f7836cbdd2511296263ecaf03135f3ef5d089260/DSCResources/MSFT_xADPrincipalNameSuffix/MSFT_xADPrincipalNameSuffix.psm1#L152)):*
> SPNSuffixNotInDesiredState

Should be `SpnSuffixNotInDesiredState` (Pascal Case), the same as it is in the strings-file already.

---

*[DSCResources/MSFT_xADPrincipalNameSuffix/MSFT_xADPrincipalNameSuffix.psm1, line 160 at r2](https://reviewable.io:443/reviews/powershell/xactivedirectory/178#-L3sPK1fXG9mH4UJw3sA:-L3sPK1fXG9mH4UJw3sB:b-cxfbnl) ([raw file](https://github.com/powershell/xactivedirectory/blob/f7836cbdd2511296263ecaf03135f3ef5d089260/DSCResources/MSFT_xADPrincipalNameSuffix/MSFT_xADPrincipalNameSuffix.psm1#L160)):*
> ```PowerShell
>                 if ($suffix -in $forest.SPNSuffixes)
>                 {
>                     Write-Verbose -Message ($localizedData.SPNSuffixNotInDesiredState -f $suffix)
> ```

Same as previous comment.

---

*[DSCResources/MSFT_xADPrincipalNameSuffix/MSFT_xADPrincipalNameSuffix.psm1, line 200 at r2](https://reviewable.io:443/reviews/powershell/xactivedirectory/178#-L3sPjU557bQfE35Ozd-:-L3sPjU557bQfE35Ozd0:b-5hvcwi) ([raw file](https://github.com/powershell/xactivedirectory/blob/f7836cbdd2511296263ecaf03135f3ef5d089260/DSCResources/MSFT_xADPrincipalNameSuffix/MSFT_xADPrincipalNameSuffix.psm1#L200)):*
> $setParams

Could we change this to `$setADForestParameters` to avoid abbreviations and more clearly show what parameters we are building (especially when reviewing :smile:)?

---

*[DSCResources/MSFT_xADPrincipalNameSuffix/MSFT_xADPrincipalNameSuffix.psm1, line 200 at r2](https://reviewable.io:443/reviews/powershell/xactivedirectory/178#-L3sPy2156MRIIK2ril0:-L3sPy2156MRIIK2ril1:bo8p4le) ([raw file](https://github.com/powershell/xactivedirectory/blob/f7836cbdd2511296263ecaf03135f3ef5d089260/DSCResources/MSFT_xADPrincipalNameSuffix/MSFT_xADPrincipalNameSuffix.psm1#L200)):*
> @{Identity = $ForestName}

Please change the hash tables according to the style guideline. Throughout.

https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md#correct-format-for-hashtables-or-objects

---

*[DSCResources/MSFT_xADPrincipalNameSuffix/MSFT_xADPrincipalNameSuffix.psm1, line 208 at r2](https://reviewable.io:443/reviews/powershell/xactivedirectory/178#-L3sQsUzc67f7ADlaWPQ:-L3sQsUzc67f7ADlaWPR:buvjj0m) ([raw file](https://github.com/powershell/xactivedirectory/blob/f7836cbdd2511296263ecaf03135f3ef5d089260/DSCResources/MSFT_xADPrincipalNameSuffix/MSFT_xADPrincipalNameSuffix.psm1#L208)):*
> ```PowerShell
>     if($Ensure -eq 'Present')
>     {
>         $action = 'Replace'
> ```

If we use replace, that means any manually added suffixes will me removed? If so, maybe we should add only the one that is missing? 

If we should have the option of replacing all in the forest, then maybe we should have three parameters; 
- `UserPrincipalNameSuffix` - This we replace all UPN in the forest. Cannot be used at the same time as `UserPrincipalNameSuffixToInclude` and `UserPrincipalNameSuffixToExclude`
- `UserPrincipalNameSuffixToInclude` - This add only these UPN's. Can be used at the same time as `UserPrincipalNameSuffixToExclude`.
- `UserPrincipalNameSuffixToExclude` - This will remove only these UPN's. Can be used at the same time as `UserPrincipalNameSuffixToInclude`

---

*[DSCResources/MSFT_xADPrincipalNameSuffix/MSFT_xADPrincipalNameSuffix.schema.mof, line 4 at r2](https://reviewable.io:443/reviews/powershell/xactivedirectory/178#-L3sLUmlPCpgym_21B-j:-L3sLUmlPCpgym_21B-k:b-7rj4ga) ([raw file](https://github.com/powershell/xactivedirectory/blob/f7836cbdd2511296263ecaf03135f3ef5d089260/DSCResources/MSFT_xADPrincipalNameSuffix/MSFT_xADPrincipalNameSuffix.schema.mof#L4)):*
> ```
> class MSFT_xADPrincipalNameSuffix : OMI_BaseResource
> {
>     [Key, Description("Specifies the target Active Directory forest for the change")] String ForestName;
> ```

Could we add a '.' to the end of the sentence (for the description)?

---

*[DSCResources/MSFT_xADPrincipalNameSuffix/en-us/MSFT_xADPrincipalNameSuffix.strings.psd1, line 4 at r2](https://reviewable.io:443/reviews/powershell/xactivedirectory/178#-L3sL6FXM8ge_TnjTwWe:-L3sL6FXM8ge_TnjTwWf:b-4fyyvl) ([raw file](https://github.com/powershell/xactivedirectory/blob/f7836cbdd2511296263ecaf03135f3ef5d089260/DSCResources/MSFT_xADPrincipalNameSuffix/en-us/MSFT_xADPrincipalNameSuffix.strings.psd1#L4)):*
> User Principal Name Suffix for '{0}' not in the desired state.

Could we add '...for forest '{0}'...', because it's nearly identical to the text in `UpnSuffixNotInDesiredState`.

---

*[DSCResources/MSFT_xADPrincipalNameSuffix/en-us/MSFT_xADPrincipalNameSuffix.strings.psd1, line 5 at r2](https://reviewable.io:443/reviews/powershell/xactivedirectory/178#-L3sLNO2o8Eh9PYIAPoz:-L3sLNO2o8Eh9PYIAPp-:b-cxfbnl) ([raw file](https://github.com/powershell/xactivedirectory/blob/f7836cbdd2511296263ecaf03135f3ef5d089260/DSCResources/MSFT_xADPrincipalNameSuffix/en-us/MSFT_xADPrincipalNameSuffix.strings.psd1#L5)):*
> ```PowerShell
>     GetForest = Getting forest suffix information from {0}.
>     ForestUpnSuffixNotInDesiredState = User Principal Name Suffix for '{0}' not in the desired state.
>     ForestSpnSuffixNotInDesiredState = Service Principal Name Suffix for '{0}' not in the desired state.
> ```

Same as previous comment.

---

*[Tests/Unit/MSFT_xADPrincipalNameSuffix.Tests.ps1, line 1 at r2](https://reviewable.io:443/reviews/powershell/xactivedirectory/178#-L3sSxIIC_NBDpCjDIDJ:-L3sSxIIC_NBDpCjDIDK:b-oxr10e) ([raw file](https://github.com/powershell/xactivedirectory/blob/f7836cbdd2511296263ecaf03135f3ef5d089260/Tests/Unit/MSFT_xADPrincipalNameSuffix.Tests.ps1#L1)):*
> $Global:

Should be `$global` (lower-.case 'g'). Throughout.
https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md#script-environment-and-global-variable-names-include-scope

---

*[Tests/Unit/MSFT_xADPrincipalNameSuffix.Tests.ps1, line 20 at r2](https://reviewable.io:443/reviews/powershell/xactivedirectory/178#-L3sT7JfLq8hmIqiCg6l:-L3sT7JfLq8hmIqiCg6m:b-944dlg) ([raw file](https://github.com/powershell/xactivedirectory/blob/f7836cbdd2511296263ecaf03135f3ef5d089260/Tests/Unit/MSFT_xADPrincipalNameSuffix.Tests.ps1#L20)):*
> ```PowerShell
> {
>     InModuleScope $Global:DSCResourceName {
> ```

Can we remove this extra blank line?

---

*[Tests/Unit/MSFT_xADPrincipalNameSuffix.Tests.ps1, line 24 at r2](https://reviewable.io:443/reviews/powershell/xactivedirectory/178#-L3sVOYUGnxjaSr4YS2B:-L3sVOYUGnxjaSr4YS2C:budrvrk) ([raw file](https://github.com/powershell/xactivedirectory/blob/f7836cbdd2511296263ecaf03135f3ef5d089260/Tests/Unit/MSFT_xADPrincipalNameSuffix.Tests.ps1#L24)):*
> $testpresentParams

Please use camelCase on local variables; `$testPresentParams` (upper 'P'). Throughout.

---

*[Tests/Unit/MSFT_xADPrincipalNameSuffix.Tests.ps1, line 34 at r2](https://reviewable.io:443/reviews/powershell/xactivedirectory/178#-L3sT5PaiQxrpVdfol2M:-L3sT5PaiQxrpVdfol2N:b-944dlg) ([raw file](https://github.com/powershell/xactivedirectory/blob/f7836cbdd2511296263ecaf03135f3ef5d089260/Tests/Unit/MSFT_xADPrincipalNameSuffix.Tests.ps1#L34)):*
> ```PowerShell
>         $testAbsentParams['Ensure'] = 'Absent'
> 
>     
> ```

Can we remove this extra blank line?

---

*[Tests/Unit/MSFT_xADPrincipalNameSuffix.Tests.ps1, line 47 at r2](https://reviewable.io:443/reviews/powershell/xactivedirectory/178#-L3sTKyaI5waL0nsrwbf:-L3sTKyaI5waL0nsrwbg:b5erp3h) ([raw file](https://github.com/powershell/xactivedirectory/blob/f7836cbdd2511296263ecaf03135f3ef5d089260/Tests/Unit/MSFT_xADPrincipalNameSuffix.Tests.ps1#L47)):*
> Mock Assert-Module

Please use named parameters. `Mock -CommandName Assert-Module`. Throughout. 

---

*[Tests/Unit/MSFT_xADPrincipalNameSuffix.Tests.ps1, line 47 at r2](https://reviewable.io:443/reviews/powershell/xactivedirectory/178#-L3sTUKpiWblSbfIPTGM:-L3sTUKpiWblSbfIPTGN:bs9q47l) ([raw file](https://github.com/powershell/xactivedirectory/blob/f7836cbdd2511296263ecaf03135f3ef5d089260/Tests/Unit/MSFT_xADPrincipalNameSuffix.Tests.ps1#L47)):*
> -MockWith { }

This parameter is not necessary when there is no need to mock with any code. Throughout.

---

*[Tests/Unit/MSFT_xADPrincipalNameSuffix.Tests.ps1, line 56 at r2](https://reviewable.io:443/reviews/powershell/xactivedirectory/178#-L3sTjdyFJGxYBlmOoCL:-L3sTjdzqWFyvE7sdtJn:ba85syl) ([raw file](https://github.com/powershell/xactivedirectory/blob/f7836cbdd2511296263ecaf03135f3ef5d089260/Tests/Unit/MSFT_xADPrincipalNameSuffix.Tests.ps1#L56)):*
> ```PowerShell
> 
>             It 'Should Return a "System.Collections.Hashtable" object type' {
>                 $targetResource -is [System.Collections.Hashtable] | Should Be $true
> ```

Nitpick: This could be changed to`$targetResource | Should -BeOfType [System.Collections.Hashtable]`

---

*[Tests/Unit/MSFT_xADPrincipalNameSuffix.Tests.ps1, line 60 at r2](https://reviewable.io:443/reviews/powershell/xactivedirectory/178#-L3sUC_3UeO0P0T9na_x:-L3sUC_3UeO0P0T9na_y:b5ap7sp) ([raw file](https://github.com/powershell/xactivedirectory/blob/f7836cbdd2511296263ecaf03135f3ef5d089260/Tests/Unit/MSFT_xADPrincipalNameSuffix.Tests.ps1#L60)):*
> Should be

We try to write these as `Should Be` (upper 'B') , or in the new Pester v4 format `Should -Be`. Throughout.

---

*[Tests/Unit/MSFT_xADPrincipalNameSuffix.Tests.ps1, line 73 at r2](https://reviewable.io:443/reviews/powershell/xactivedirectory/178#-L3sUmMj6pFJEtchzZwR:-L3sUmMj6pFJEtchzZwS:b-944dlg) ([raw file](https://github.com/powershell/xactivedirectory/blob/f7836cbdd2511296263ecaf03135f3ef5d089260/Tests/Unit/MSFT_xADPrincipalNameSuffix.Tests.ps1#L73)):*
> ```PowerShell
>         
>         Describe "$($Global:DSCResourceName)\Test-TargetResource" {
> ```

Can we remove this extra blank line?

---

*[Tests/Unit/MSFT_xADPrincipalNameSuffix.Tests.ps1, line 80 at r2](https://reviewable.io:443/reviews/powershell/xactivedirectory/178#-L3sVB3dzQt8Wuh2LOGE:-L3sVB3dzQt8Wuh2LOGF:bekubdp) ([raw file](https://github.com/powershell/xactivedirectory/blob/f7836cbdd2511296263ecaf03135f3ef5d089260/Tests/Unit/MSFT_xADPrincipalNameSuffix.Tests.ps1#L80)):*
> matche

Typo here, I think it should be 'match'?

---

*[Tests/Unit/MSFT_xADPrincipalNameSuffix.Tests.ps1, line 105 at r2](https://reviewable.io:443/reviews/powershell/xactivedirectory/178#-L3sW02Tg8FfFseaBbPl:-L3sW02Tg8FfFseaBbPm:b-emp50) ([raw file](https://github.com/powershell/xactivedirectory/blob/f7836cbdd2511296263ecaf03135f3ef5d089260/Tests/Unit/MSFT_xADPrincipalNameSuffix.Tests.ps1#L105)):*
> ```PowerShell
>                 Set-TargetResource @testPresentParams -Credential $testCredential
> 
>                 Assert-MockCalled Set-ADForest -ParameterFilter { $Credential -eq $testCredential } -Scope It             
> ```

Please used named parameters `-CommandName`.  Also, it wouldn't hurt if we add `-Exactly -Times 1` to know that it is actually called so many times as expected. Throughout.

---

*[Tests/Unit/MSFT_xADPrincipalNameSuffix.Tests.ps1, line 109 at r2](https://reviewable.io:443/reviews/powershell/xactivedirectory/178#-L3sWmoNJqblB3jfdn45:-L3sWmoNJqblB3jfdn46:bdsrbwf) ([raw file](https://github.com/powershell/xactivedirectory/blob/f7836cbdd2511296263ecaf03135f3ef5d089260/Tests/Unit/MSFT_xADPrincipalNameSuffix.Tests.ps1#L109)):*
> .replace

Can we change this to `.Replace`. Upper 'R'. Throughout.

---

*[Tests/Unit/MSFT_xADPrincipalNameSuffix.Tests.ps1, line 117 at r2](https://reviewable.io:443/reviews/powershell/xactivedirectory/178#-L3sWd-bJXmcFwc8dYuw:-L3sWd-bJXmcFwc8dYux:b-k1ih47) ([raw file](https://github.com/powershell/xactivedirectory/blob/f7836cbdd2511296263ecaf03135f3ef5d089260/Tests/Unit/MSFT_xADPrincipalNameSuffix.Tests.ps1#L117)):*
> .remove

Can we change this to `.Remove`. Upper 'R'. Throughout.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xactivedirectory/178)*

**Comment by regedit32** [comment]
@johlju Thanks for the review, I'll make those updates early this week.

**Comment by johlju** [comment]
@regedit32 Have you had the chance to look at the review comments? This PR also needs to be rebase against dev (using `git rebase`).

**Comment by regedit32** [comment]
Thanks @johlju .  I started making the changes, but it ended up being a larger rework and I haven't had a chance to get back to it.

**Comment by johlju** [comment]
@regedit32 No worries, then I know you are still active on this PR. I will wait for you to update the review comments once you are done. 🙂

**Comment by johlju** [comment]
@regedit32 don't want to rush you in any way, just checking in since it was a month since the last update. Do you see you have a chance to continue the work on this PR?

**Comment by regedit32** [comment]
@johlju I hope to eventually get back to this and make the changes, but it's a little off my radar at the moment.

**Comment by johlju** [comment]
@regedit32 Thanks for the update!

**Comment by johlju** [comment]
@regedit32 Awesome work on this! 😃

**Comment by johlju** [comment]
@regedit32 Awesome work on this one as usual! Thank you! 😃

**Pull request merged**
