### PR TITLE
FIX for Issue #152

### PR DESCRIPTION
**Pull request by RobBiddle**
Fix for this issue: https://github.com/PowerShell/xActiveDirectory/issues/152

Functionality of xADGroup is only changed when setting Property 'MembershipAttribute' with a value of 'DistinguishedName'.

When 'DistinguishedName' is used, each Group Member DN String is evaluated to determine the AD Domain of the Group Member Object and the ObjectClass.  Then Get-ADComputer,Get-ADGroup or Get-ADUser is called, specifying the appropriate Domain to query.  Once the Object is retrieved then Add-ADGroupMember is able to successfully add the members, even if they exist in another domain.

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xactivedirectory/174)

### CODE REVIEW

**Comment by johlju** [comment]
@RobBiddle Sorry that it took so long to review you PR. Could you please add unit tests that tests this change?

**Comment by johlju** [comment]
Labeling as abandoned since it has gone 14 days until last update. An abandoned PR can be continued by another contributor. The abandoned label will be removed if work on the PR is taken up again.

**Comment by nyanhp** [comment]
Hi @johlju , how can I continue the PR? My customer has the same requirement.

I have taken all changes from @RobBiddle and added the necessary test cases here: https://github.com/nyanhp/xActiveDirectory/tree/multidomainmembers
I have of course branched off the current dev branch.

**Comment by johlju** [comment]
You can send in another PR. Reference this PR `Close #174`. 
Please also read here https://github.com/PowerShell/DscResources/blob/master/GettingStartedWithGitHub.md#how-to-continue-working-on-a-pull-request-pr-when-an-author-contributor-is-unable-to-complete-it

**Pull request closed without merging**
