### PR TITLE
xADDomainController: Add RODC Creation Support

### LINKED ISSUE #40: Add RODC Creation Support
Is there any plan to add support to install a server as an RODC?

### PR DESCRIPTION
**Pull request by SSvilen**
#### Pull Request (PR) description
Adding support for Read-only Domain Controllers creation.

#### This Pull Request (PR) fixes the following issues
- Fixes #40 

#### Task list
- [x] Added an entry under the Unreleased section in the CHANGELOG.md.
      Entry should say what was changed, and how that affects users (if applicable).
- [x] Resource documentation added/updated in resource directory README.md.
- [x] Resource parameter descriptions added/updated in schema.mof
      and comment-based help.
- [x] Comment-based help added/updated.
- [x] Localization strings added/updated in all localization files as appropriate.
- [x] Examples appropriately added/updated.
- [x] Unit tests added/updated. See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [ ] Integration tests added/updated (where possible). See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [x] New/changed code adheres to [DSC Resource Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md) and [Best Practices](https://github.com/PowerShell/DscResources/blob/master/BestPractices.md).

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xactivedirectory/390)

### CODE REVIEW

**Comment by johlju** [comment]
@SSvilen Thank you for this PR! Really looking forward getting this through. Before I review this, could you please resolve the tabs -> spaces, and the indentation has been changed too. See the screenshot here from reviewable. Also see the failing test here (failing because of tabs):
https://ci.appveyor.com/project/PowerShell/xactivedirectory/builds/25479763?fullLog=true#L300

image

**Comment by johlju** [comment]
@SSvilen Let me know if I can be of any assistance. 🙂

**Comment by johlju** [comment]
For the [PSScriptAnalyzer failing tests[(https://ci.appveyor.com/project/PowerShell/xactivedirectory/builds/25481046?fullLog=true#L861) if the parameter need to contain 'Password' then we need to override that specific rule and a justification, see example. https://github.com/PowerShell/xActiveDirectory/blob/727474acdee1f9930b083991d602cb3f5054a769/DSCResources/MSFT_xADDomainTrust/MSFT_xADDomainTrust.psm1#L111

This PR still suggest (wrongly) to change the indentation of a lot of code, can you please go through the code an fix the indentation back? See example of this PR suggest to change the indentation here.
https://github.com/PowerShell/xActiveDirectory/pull/390/files#diff-c2e4729ff3e75e56c38b6e0c2e16a181

I can help take a look at the other failing tests, but it can take a while, I will be traveling for a week. So in the meantime please see if you can resolve them. 🙂

**Comment by X-Guardian** [comment]
Hi @SSvilen, to help with the PSScriptAnalyzer `AvoidUsingPlainTextForPassword` errors, the analyzer rule is really dumb and is just looking for parameters that contain any of the following strings: "Password", "Passphrase", "Cred", "Credential", so it it tripping on your `DenyPasswordReplicationAccountName` and `AllowPasswordReplicationAccountName` parameters. You can either override it as @johlju says, or rename the parameter to not contain the `password` string. i.e. `Passwd`, or `Pwd` etc.

**Comment by johlju** [comment]
I think we should not use abbreviations in parameter/property named. I rather we override it instead. Or use another word instead of 'Password'.

**Comment by johlju** [comment]
@SSvilen I saved the example below before the wiki content was regenerated. I saved it in case you needed it to create the example file (see review comment)

---

This configuration will add a read-only domain controller to the domain contoso.com and specify a list of account, whose passwords are allowed/denied for synchronisation.

```powershell
Configuration RODC_Config
{
    param
    (
        [Parameter(Mandatory = $true)]
        [ValidateNotNullOrEmpty()]
        [System.Management.Automation.PSCredential]
        $DomainAdministratorCredential
    )

    Import-DscResource -ModuleName PSDscResources
    Import-DscResource -ModuleName xActiveDirectory

    node localhost
    {
        WindowsFeature 'InstallADDomainServicesFeature' {
            Ensure = 'Present'
            Name   = 'AD-Domain-Services'
        }

        WindowsFeature 'RSATADPowerShell' {
            Ensure    = 'Present'
            Name      = 'RSAT-AD-PowerShell'

            DependsOn = '[WindowsFeature]InstallADDomainServicesFeature'
        }

        xWaitForADDomain 'WaitForestAvailability' {
            DomainName           = 'contoso.com'
            DomainUserCredential = $DomainAdministratorCredential
            RetryCount           = 10
            RetryIntervalSec     = 120

            DependsOn            = '[WindowsFeature]RSATADPowerShell'
        }

        xADDomainController 'RODC' {
            DomainName                    = 'contoso.com'
            DomainAdministratorCredential = $DomainAdministratorCredential
            SafemodeAdministratorPassword = $DomainAdministratorCredential
            ReadOnlyReplica               = $true
            SiteName = 'Default-First-Site-Name'
            AllowPasswordReplicationAccountName = 'pvdi.test1','pvdi.test'
            DenyPasswordReplicationAccountName =  'SVC_PVS','TA2SCVMM'
            DependsOn                     = '[xWaitForADDomain]WaitForestAvailability'
        }
    }
}
```

**Comment by johlju** [comment]
Easiest is to connect your own AppVeyor account (it is free for open source) and add your fork of xActiveDirectory as project in you AppVeyor account. Then you can branch out to another branch (e.g `debug-RODCSupport`), then when you push to your "debug" branch without spamming with debug commits in the PR. 🙂 

Either way, you can connect to the RDP session by enabling it in the appveyor.yml. Then you can run tests manually in the AppVeyor build worker. See here https://www.appveyor.com/docs/how-to/rdp-to-build-worker/

I wonder if this problem is unrelated to your PR (bug in the tests), but it started to show now when the code changed. Either way, I can't merge until all tests pass. 😕  But I will help you debug this after Tuesday unless you solved it by then (off on a mini-vaction now, jsyt catching upp on stugg on the train ride). 😄

**Comment by SSvilen** [comment]
I found another problem, that I have to fix, so I'll just close that PR and open a new one with cleaner commit history. This branch history turned into a mess.

**Pull request closed without merging**
