### PR TITLE
xADUser: Add PasswordNeverResets parameter

### LINKED ISSUE #219: Repeated runs - Passwords reset
Wondering what the approach is when using this in an environment endeavouring for everything-as-code.

I have AD set up, and wish to store configuration of users and groups as code.

This means that the DSC will run periodically, eg when it has changed. It appears that this is resetting the passwords of any users who have changed them.

1. Users should be able to change their passwords.
2. I want to set a strong password automatically, which will be distributed to them.

Are there any guides or approaches I should take?

At the moment I am setting up users with the following property:

`Password = New-Object System.Management.Automation.PSCredential ("matt.canty", $DefaultPassword)`

### PR DESCRIPTION
**Pull request by kingsleyck**
#### Pull Request (PR) description
In its current state, xADUser will create a user account and apply the password if specified. On subsequent runs, this password is re-applied. This behavior is a challenge when applying xADUser to managing users via code in a production environment. This PR addresses this issue by enabling xADUser to create an account with a declared password and then also ignore password drift during future DSC application if PasswordNeverResets = $true. The default behavior is $false, which retains existing behavior of the resource.

#### This Pull Request (PR) fixes the following issues
- Fixes #219 

#### Task list
- [x] Added an entry under the Unreleased section of the change log in the README.md.
      Entry should say what was changed, and how that affects users (if applicable).
- [x] Resource documentation added/updated in README.md.
- [x] Resource parameter descriptions added/updated in README.md, schema.mof
      and comment-based help.
- [x] Comment-based help added/updated.
- [x] Unit tests added/updated. See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
(https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [x] New/changed code adheres to [DSC Resource Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md) and [Best Practices](https://github.com/PowerShell/DscResources/blob/master/BestPractices.md).

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xactivedirectory/227)

### CODE REVIEW

**Comment by johlju** [comment]
Closing and reopening directly to kick of the status check bots - none seem to have finished (probably due to some GitHub glitch).

**Comment by kingsleyck** [comment]
Accepted CLA.

**Comment by kingsleyck** [comment]
I believe all of the comments have been addressed. I also took some time to resolve the existing PSScriptAnalyzer failures.

**Comment by kingsleyck** [comment]
Requested changes made.

**Comment by johlju** [comment]
@kingsleyck Thank you for this! Great work! 😃

**Comment by kingsleyck** [comment]
Thanks, if I can contribute in other areas I will definitely do so.

**Comment by johlju** [comment]
@kingsleyck you are more than welcome! Looking forward to more PR's! 🙂

**Pull request merged**
