### PR TITLE
Converted $Members to an Array

### PR DESCRIPTION
**Pull request by mcollera**
Get will fail if their is only one member.

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xactivedirectory/173)

### CODE REVIEW

**Comment by matt2005** [comment]
Wouldn't it be better to change [Line 94](https://github.com/PowerShell/xActiveDirectory/blob/dev/DSCResources/MSFT_xADGroup/MSFT_xADGroup.psm1#L94) to 
```
[System.Array]$adGroupMembers = (Get-ADGroupMember @adGroupParams).$MembershipAttribute;
```
Fixes #161

**Comment by johlju** [comment]
I agree with @matt2005. Then it's an array from the start, if more work need to be done on it in the future.

**Comment by mcollera** [comment]
@matt2005 agreed. Change made

**Comment by regedit32** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xactivedirectory/173#-:-L3ey5xDBb1NhaL9BmoM:bnfp4nl)*

**Pull request merged**
