### PR TITLE
xADUser: Add TrustedForDelegation parameter to support Kerberos delegation

### PR DESCRIPTION
**Pull request by pshamus**
#### Pull Request (PR) description
Added new parameter to allow Kerberos delegation to be set on an Active Directory user.

#### This Pull Request (PR) fixes the following issues
None

#### Task list
- [x] Added an entry under the Unreleased section of the change log in the README.md.
      Entry should say what was changed, and how that affects users (if applicable).
- [x] Resource documentation added/updated in README.md.
- [x] Resource parameter descriptions added/updated in README.md, schema.mof
      and comment-based help.
- [ ] Comment-based help added/updated.
- [ ] Localization strings added/updated in all localization files as appropriate.
- [ ] Examples appropriately added/updated.
- [x] Unit tests added/updated. See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [ ] Integration tests added/updated (where possible). See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [x] New/changed code adheres to [DSC Resource Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md) and [Best Practices](https://github.com/PowerShell/DscResources/blob/master/BestPractices.md).

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xactivedirectory/241)

### CODE REVIEW

**Comment by pshamus** [comment]
Any update as to the status of this PR? Is there anything missing or are there any comments/questions?

**Comment by johlju** [comment]
I just haven't gotten the time to reviewing the PR's in this repo yet. I will get to this PR as soon as I can. In the mean while, I just merged a PR that resolved failing tests. Please rebase this PR when you have chance.

**Comment by pshamus** [comment]
No worries, thanks for jumping on this!

**Comment by pshamus** [comment]
Okay, changes applied. Please let me know if you need anything else. This is my first public PR so it's a learning experience.

**Comment by johlju** [comment]
@pshamus so happy you are here a contributing! We all started out with out very first PR, we are all still learning still. 😃 The rebase looks good, great work!. Although I just merged another PR. So you need to rebase again. :/ But maybe we can see it as a good learning experience though, learning how to rebase 😄 

Just do what you did before again and I will make sure to merge this one in next. 🙂

**Comment by pshamus** [comment]
@johlju Okay, done. And no worries on me having to do this again. It's helpful from a learning perspective. :)

**Comment by johlju** [comment]
@pshamus merged now! Thanks for this! 😃 Looking forward to your next PR! 🙂

**Pull request merged**
