### PR TITLE
xADDomainTrust: Refactor resource and add tests

### LINKED ISSUE #324: xADDomainTrust: Missing unit test for the resource
We should add a unit test for this resource.

### LINKED ISSUE #337: xADDomainTrust: This resource is missing comment-based help
This resource is missing comment-based help for the functions.

### LINKED ISSUE #348: xADDomainTrust: Integration tests is missing for this resource
We should add integration tests for this resource.

### PR DESCRIPTION
**Pull request by johlju**
#### Pull Request (PR) description
- Changes to xActiveDirectory
  - Added new helper functions in xActiveDirectory.Common.
    - New-CimCredentialInstance
    - Add-TypeAssembly
    - New-ADDirectoryContext
- Changes to xADDomainTrust
  - Refactored the resource to enable unit tests, and at the same time changed
    it to use the same code pattern as the resource xADObjectEnabledState.
  - Added unit tests (issue #324).
  - Added comment-based help (issue #337).
  - Added integration tests (issue #348).

The integration test result is provided in this gist https://gist.github.com/johlju/62c72d492c28604355f602b2aad67668.

#### This Pull Request (PR) fixes the following issues
- Fixes #324 
- Fixes #337 
- Fixes #348 

#### Task list

- [x] Added an entry under the Unreleased section in the CHANGELOG.md.
      Entry should say what was changed, and how that affects users (if applicable).
- [x] Resource documentation added/updated in resource directory README.md.
- [x] Resource parameter descriptions added/updated in schema.mof
      and comment-based help.
- [x] Comment-based help added/updated.
- [x] Localization strings added/updated in all localization files as appropriate.
- [ ] Examples appropriately added/updated.
- [x] Unit tests added/updated. See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [x] Integration tests added/updated (where possible). See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [x] New/changed code adheres to [DSC Resource Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md) and [Best Practices](https://github.com/PowerShell/DscResources/blob/master/BestPractices.md).

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xactivedirectory/423)

### CODE REVIEW

**Comment by johlju** [comment]
If someone in the community would like to review this I would be grateful. It's a big one, so probably gonna take a bit of time. 🙂

**Comment by johlju** [comment]
@PlagueHO if you have time I would love it if you could review this one. It is a big one since the whole resource was rewritten since it used a abnormal pattern. 

*Since the same logic was used as in the current resource, there are two big issues (but edge cases) that I wont fix in this PR, submitted issue https://github.com/PowerShell/xActiveDirectory/issues/424 and https://github.com/PowerShell/xActiveDirectory/issues/425.*

**Comment by PlagueHO** [comment]
I'm on it.

**Comment by johlju** [comment]
@PlagueHO Ready for review again. 

After a few commits I finally got it to pass the tests. Script Analyzer did not like my new function. ;) I tried to use multiple types in the `OutputType` as should be valid syntax, but PSScriptAnalayzer did not like that. Submitted an issue for it to PSScriptAnalayzer repo. I was not allowed to override that rule either as per the test framework, so I had to revert back to what PSScriptAnalyzer expected it to be.

**Comment by johlju** [comment]
@PlagueHO ready for review again 😃

**Comment by johlju** [comment]
@PlagueHO thank you for the review! I agree that we can call it a tuple. 😄

**Pull request merged**
