### PR TITLE
Add changes from version 2.3

### PR DESCRIPTION
**Pull request by vors**
I found that PSGallery contains a newer version of the module.
@GoateePFE can you please, review this changes?

### CODE REVIEW

**Comment by GoateePFE** [comment]
Give me a few days.

**Comment by GoateePFE** [comment]
Eeewww. This one looks a little messy.  On first glance this could take a while to sort out.  I see one particular change in the xADUser that is not good (regarding enabled/disabled account).  Unfortunately I don't have the bandwidth to look at this for two weeks.

**Comment by GoateePFE** [comment]
I looked at this briefly.  Basically I would suggest just accepting all the change to merge in except for xWaitForADDomain.  For that one the previous version looks better.  Can you override with the previous version?  Then I can make a pass to fix the xADUser again later.

**Comment by vors** [comment]
Sure, will do.

**Comment by vors** [comment]
I kind of slip from this PR

**Pull request merged**
