### PR TITLE
xADDomainController: Added new parameter IsGlobalCatalog

### LINKED ISSUE #75: xADDomain and xADDomainController: Ability to enable/disable Global Catalog
Currently all DC's promoted using xADDomain and xADDomainController are set as GC's.

This is fine for the first DC on in a domain (or site), but usually undesirable for additional DC's added to a domain (usually only one GC per site is recommended).

Could we add a parameter to disable GC when promoting a DC? If the DC is already promoted then this switch would need to disable GC on the DC by calling something like this:
http://blogs.msmvps.com/richardsiddaway/2012/03/18/enable-global-catalog/

This probably only needs to be added to the xADDomainController resource because there must always be at least one GC in a domain so the xADDomain should always create a GC, although, if the first DC on the domain (that was promoted using xADDomain) needed to have the GC removed then xADDomain should also support enabling/disabling the GC. Thoughts?

I don't think that this needs to be a tri-state switch (like the DNS one).

### PR DESCRIPTION
**Pull request by johlju**
#### Pull Request (PR) description
- Changes to xADDomainController
  - Added new parameter to disable or enable the Global Catalog (GC) (issue #75).
  - Fixed a bug with the parameter `InstallationMediaPath` that it would
    not be added if it was specified in a configuration. Now the parameter
    `InstallationMediaPath` is correctly passed to `Install-ADDSDomainController`.
  - Refactored the resource with major code cleanup and localization.
  - Updated unit tests to latest unit test template, and refactored the
    tests for the function 'Set-TargetResource'.
  - Improved test code coverage.

#### This Pull Request (PR) fixes the following issues
- Fixes #75
- Closes #135

#### Task list

- [x] Added an entry under the Unreleased section of the change log in the README.md.
      Entry should say what was changed, and how that affects users (if applicable).
- [x] Resource documentation added/updated in README.md.
- [x] Resource parameter descriptions added/updated in README.md, schema.mof
      and comment-based help.
- [x] Comment-based help added/updated.
- [x] Localization strings added/updated in all localization files as appropriate.
- [x] Examples appropriately added/updated.
- [x] Unit tests added/updated. See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [ ] Integration tests added/updated (where possible). See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [x] New/changed code adheres to [DSC Resource Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md) and [Best Practices](https://github.com/PowerShell/DscResources/blob/master/BestPractices.md).

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xactivedirectory/255)

### CODE REVIEW

**Comment by johlju** [comment]
@nyanhp, @devopsjesus, @rchristman89 would anyone of you (or all) help me an review this PR? 😃  Let me know if you need any help to get started with reviewing. I'm here or on [(join) Slack](https://j.mp/psslack).

**Comment by johlju** [comment]
@kungfu71186 Many thanks for the review 🙇 I will get on these in a day or so!

**Comment by johlju** [comment]
@kungfu71186 You mind looking at this again? I refactored it a bit, so a little more to review though. 🙂

**Comment by kungfu71186** [comment]
@johlju looks pretty good on my end. Good job!

**Comment by kungfu71186** [comment]
@johlju not sure if anyone else needs to review, but looks good to me.

**Comment by johlju** [comment]
@kungfu71186 I just push another commit, can you sign off on that too? I found out the hard way when manually doing an integration tests. The 
`Install-ADDSDomainController` just halted. My config used the same account for both the primary and secondary. Secondary needed the domain account, while primary used the local account. :)

No, no other need to review. Your review and my manual test should be enough. 😃 Thank you!

**Comment by johlju** [comment]
@kungfu71186 I usually get the spelling right, but the grammar is not my strong suit (English is second language), so if you see me do grammatical errors, then please correct me. :) @PlagueHO are usually good at spotting those for me too. 😄

**Comment by kungfu71186** [comment]
@johlju no worries, English is my first language, but sometimes it seems like it's my third lol.

**Comment by kungfu71186** [comment]
@johlju Ran through a clean DC install with 2019. One issue I ran into was the windows feature `AD-Domain-Service` is required, without this you can't run `Install-ADDSDomainController` This isn't in the examples either.

Another strange issue is after I rebooted the machine, it says that it is a DC, but asked to finish the promotion. not sure why. Maybe a 2019 thing? Could also be my environment. 

Found one other issue. If I do something like:

DomainName: mydomain.contoso.com

Config looks like:
```
        xADDomainController 'DomainControllerMinimal'
        {
            DomainName                    = 'mydomain'
            DomainAdministratorCredential = $DomainAdministratorCredential
            SafemodeAdministratorPassword = $DomainAdministratorCredential
        }
```
It fails the check because of:

https://github.com/johlju/xActiveDirectory/blob/80f5c2b1fc08ac3627987b8167a97550c16a99ac/DSCResources/MSFT_xADDomainController/MSFT_xADDomainController.psm1#L134

Its comparing using the fqdn. I think this check is sufficient enough:
https://github.com/johlju/xActiveDirectory/blob/80f5c2b1fc08ac3627987b8167a97550c16a99ac/DSCResources/MSFT_xADDomainController/MSFT_xADDomainController.psm1#L110

I think if you move: https://github.com/johlju/xActiveDirectory/blob/80f5c2b1fc08ac3627987b8167a97550c16a99ac/DSCResources/MSFT_xADDomainController/MSFT_xADDomainController.psm1#L130-L148 this into the try block, you will be ok with your check or do something like i did:

https://github.com/kungfu71186/xActiveDirectory/blob/a7dfce34d372520a82cda1601dd5054810fbfcd3/DSCResources/MSFT_xADKDSKey/MSFT_xADKDSKey.psm1#L496

Maybe we can make that a common function. Assert-IsDomainController or whatever.

**Comment by johlju** [comment]
> One issue I ran into was the windows feature AD-Domain-Service is required, without this you can't run Install-ADDSDomainController This isn't in the examples either.

It's in the example here; https://github.com/PowerShell/xActiveDirectory#examples
Those examples should really move to the Examples folder (submitted an issue for that).

> Another strange issue is after I rebooted the machine, it says that it is a DC, but asked to finish the promotion. not sure why. Maybe a 2019 thing? Could also be my environment.

I did not get this on Windows Server 2016 🤔

**Comment by johlju** [comment]
> `catch [Microsoft.ActiveDirectory.Management.ADIdentityNotFoundException]`

I actually did this and changed it in commit https://github.com/PowerShell/xActiveDirectory/pull/255/commits/d84393be18b0175522bbf6ebdd86e3c4ae7eceea

The reason I changed it because the test failed... And that is because I never actually throw the correct error it was expecting, so of course it failed. 😞 I must have been tired. 😕  

Thank you for pointing out that again for me, I will make the correction.

**Comment by johlju** [comment]
>Found one other issue. If I do something like:
>DomainName: mydomain.contoso.com

I removed the check as you pointed out, and intead make sure it returns the actual domin namein the property `DomainName`. 
But, curious, does it not work to use this? 

```powershell
        xADDomainController 'DomainControllerMinimal'
        {
            DomainName                    = 'mydomain.contoso.com'
            DomainAdministratorCredential = $DomainAdministratorCredential
            SafemodeAdministratorPassword = $DomainAdministratorCredential
        }
```
If above does not work, then I should add another example for a child domain.

**Comment by johlju** [comment]
> I think if you move this into the try block, you will be ok with your check or do something like i did:

I wanted to catch the actual error if the `Get-ADDomainController` failed, and have another try block for the rest if it was needed, but didn't seem necessary. 

> Maybe we can make that a common function. Assert-IsDomainController or whatever.

Yep, thought of that as well, but was hoping I wouldn't have to do that for this PR. But since you bring it up, lets do that. 😄

**Comment by kungfu71186** [comment]
@johlju yeah, I thought about making it into a common function when I was doing KDS, but wasn't sure it was needed elsewhere. 

I kinda prefer the producttype method just because it's quick and doesn't rely on the ad module. Let me know if you wanna make a PR for it or want me to. Probably won't be able to get to it until tomorrow though.

**Comment by johlju** [comment]
I'm looking into this, but creating `Get-DomainControllerObject` since it must return the actual object for the domain controller, not just check if it exist. But `Assert-IsDomainController` could be good to have too, buit that can be another PR. :)

**Comment by johlju** [comment]
Even if we can assume the producttype -eq 2 always mean it's a domain controller, we still need to handle the errors. 🤔

**Comment by kungfu71186** [comment]
> > Found one other issue. If I do something like:
> > DomainName: mydomain.contoso.com
> 
> I removed the check as you pointed out, and intead make sure it returns the actual domin namein the property `DomainName`.
> But, curious, does it not work to use this?
> 
> ```powershell
>         xADDomainController 'DomainControllerMinimal'
>         {
>             DomainName                    = 'mydomain.contoso.com'
>             DomainAdministratorCredential = $DomainAdministratorCredential
>             SafemodeAdministratorPassword = $DomainAdministratorCredential
>         }
> ```
> 
> If above does not work, then I should add another example for a child domain.

Yes. Fqdn works, just not the short name. 



> I'm looking into this, but creating `Get-DomainControllerObject` since it must return the actual object for the domain controller, not just check if it exist. But `Assert-IsDomainController` could be good to have too, buit that can be another PR. :)

I guess that's true. Forgot you were returning a few settings from there.

> Even if we can assume the producttype -eq 2 always mean it's a domain controller, we still need to handle the errors.

Yeah, that would probably be good, but pretty simple to do.

**Comment by johlju** [comment]
@kungfu71186 Let me know what you think of this change. Did I get all your comments? Let me know if I missed one. 

If you have the opportunity to verify this change again on Windows Server 2019, I would be grateful.

**Comment by kungfu71186** [comment]
@johlju yeah I think that was the last thing. I'll take another look and do a quick test tomorrow

**Comment by kungfu71186** [comment]
@johlju ran a quick integration test. Was able to promote and change global catalog. I did not test promoting a DC without global catalog though.

Both the short name and FQDN works as well.

I'll finish code review tomorrow though, but looks like its about ready to be merged.

**Comment by johlju** [comment]
Cool! I can test adding a 2016 DC without GC tomorrow

**Comment by kungfu71186** [comment]
@johlju Looks pretty good. Just missing a few test cases for thrown errors, non-stopping. There is an error in appveyor that needs to be fixed. Otherwise it's to be merged.

**Comment by johlju** [comment]
I'm gonna get the code coverage (thats the failing test), also seeing a strange error on Win 2016. Not sure if it is related to this change, or my configuration, but want to make sure.

**Comment by kungfu71186** [comment]
Interesting. I had only tried while the node was on the domain this time.

**Comment by johlju** [comment]
I wonder if we should do this instead `Get-ADDomainController -Filter '*' -Server 'companylab.se'`. That gives us all the domain controllers. If the `$env:COMPUTERNAME` is not part of the list returned, and the helper function `Assert-IsDomainController` returns false , then we could assume thise is not a domain controller?

**Comment by johlju** [comment]
Then we don't have to handle any errors at all. Much cleaner.

**Comment by johlju** [comment]
@kungfu71186 Can you be so kind to review/approve these changes again? 

I feel comfortable that this change should be stable and work now (it feels more stable). I refactored the unit tests for `Set-TargetResource` too, and fixed a 100% code coverage for the xADDomainController resource. 
The unit test passed locally on a Domain Controller, so they should pass in AppVeyor too, otherwise I will fix them promptly.

**Comment by johlju** [comment]
I tested this change manually by running Get and Set with Invoke-DscResource, and then I run a full configuration on a node that was not part of a domain, and it successfully rebooted as a domain controller, and also not having a global catalog. 🙂

**Comment by kungfu71186** [comment]
@johlju looks like code is good, just some grammatical issues and then ready for merge. Yay!!!

**Comment by johlju** [comment]
@kungfu71186 When you have time, please sign off on the last changes. 😃

**Comment by johlju** [comment]
I will run one more manual test in Win 2018, then I merge

**Comment by johlju** [comment]
@kungfu71186 Two additional domain controllers installed without any issue. One with GC and one without GC.

**Pull request merged**
