### PR TITLE
Add xADReplicationSubnet resource.

### PR DESCRIPTION
**Pull request by claudiospizzi**
I've added an DSC resource callled xADReplicationSubnet to add, update or remove Active Directory Replication Subnets.

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xactivedirectory/180)

### CODE REVIEW

**Comment by claudiospizzi** [comment]
@johlju @kwirkykat Any chance to review this PR before the next release?

**Comment by johlju** [comment]
@claudiospizzi I will try to review when I have time, but the day job and other maintainer responsibilities keeps me busy. 
One question though, there are a few `Set-ADReplication*` cmdlets. What if we named this resource xADReplication, and the Key was Site - for a site we could have an array of Subnets which will be added and removed as needed. Would that work, or are we looking at one cmdlet equals one resource? What is your thought?
I'm just throwing this out there so we don't end up with a lot of resource which could have been merged together.

**Comment by claudiospizzi** [comment]
@johlju If we make something like a xADReplicationSite resource to control the site and it's subnet, this can work. What I just see is, that if we want to provide additional information to the subnet like location and description, we have to add a hashtable to the resource.
Finally, a alignment of *-ADReplicationSubnet to xADReplicationSubnet is easier to maintain, but more lines are required in the configuration.
Last think: I'm a bit careful controlling sites with DSC, because removing the wrong site can bring your AD in trouble.

**Comment by johlju** [comment]
@claudiospizzi Sounds like this name is well thought then, because we want be able to provide additional information and a site can be in one location and a subnet in another location. So this resource name sounds good.

**Comment by claudiospizzi** [comment]
Updated the PR with the latest dev branch

**Comment by claudiospizzi** [comment]
@johlju As the name seems to be okay, also compared to #185, can we continue on this PR?

**Pull request merged**
