### PR TITLE
Add ODJ Support to xADComputer - Fixes #84

### LINKED ISSUE #84: Add xProvisionODJ Resource
Create a new resource for provisioning a computer in AD for ODJ. The ODJ file created can then be consumed by the xOfflineDomainJoin resource I've just [submitted to xComputerManagement](https://github.com/PowerShell/xComputerManagement/pull/27).

The main purpose of this is to allow automated provisioning of Nano Server via DSC, although it will work for other any machine.

DJOIN will be used to provision the machine in AD (/REUSE is required if already exists) and create the request blob:
```
djoin /PROVISION /DOMAIN CONTOSO.COM /MACHINE NANO1 /SAVEFILE c:\nano1-odj.txt
```

### PR DESCRIPTION
**Pull request by PlagueHO**
To be able to submit this PR I had to also resolve all the PSSA errors.

This meant I had to change a few more of the files than I'd planned - and in doing so the extra white space was removed (an absolutely awesome feature of VSCode). So sorry about all the white space removal. I know it makes the PR a PITA to review, but it only gets done once.

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xactivedirectory/100)

### CODE REVIEW

**Comment by TravisEz13** [comment]
Reviewed 13 of 16 files at r1.
Review status: 13 of 16 files reviewed at latest revision, 2 unresolved discussions.

---

*[Assert-HADC.ps1, line 7 \[r1\]](https://reviewable.io:443/reviews/powershell/xactivedirectory/100#-KK_AxJ7bnfDrRYuPgld:-KK_AxJ7bnfDrRYuPgle:-184154309) ([raw file](https://github.com/powershell/xactivedirectory/blob/b6db46aad1ab0df8ab2b31ccb242a70b2151a221/Assert-HADC.ps1#L7)):*
> ```PowerShell
> # A configuration to Create High Availability Domain Controller
> 
> $secpasswd = ConvertTo-SecureString "Adrumble@6" -AsPlainText -Force
> ```

Are these test files?  If so ,why are they not in the test folder?

---

*[DSCResources/MSFT_xADComputer/MSFT_xADComputer.schema.mof, line 16 \[r1\]](https://reviewable.io:443/reviews/powershell/xactivedirectory/100#-KK_BcAsIBYcVY7B0CV5:-KK_BcAsIBYcVY7B0CV6:1956752981) ([raw file](https://github.com/powershell/xactivedirectory/blob/b6db46aad1ab0df8ab2b31ccb242a70b2151a221/DSCResources/MSFT_xADComputer/MSFT_xADComputer.schema.mof#L16)):*
> ```
>     [Write, Description("Specifies the Active Directory Domain Services instance to connect to perform the task")] String DomainController;
>     [Write, Description("Specifies the user account credentials to use to perform the task"), EmbeddedInstance("MSFT_Credential")] String DomainAdministratorCredential;
>     [Write, Description("Specifies the full path to the Offline Domain Join Request file to create.")] String ODJRequestFile;
> ```

We should reconsider this name.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xactivedirectory/100)*

**Comment by TravisEz13** [comment]
Previous review, https://github.com/PowerShell/xActiveDirectory/pull/86, the name became RequestFile

**Comment by PlagueHO** [comment]
@TravisEz13  - cool. Leave it with me. I'll change it to RequestFile. Thanks for reviewing!

**Comment by TravisEz13** [comment]
Reviewed 2 of 16 files at r1, 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xactivedirectory/100)*

**Comment by TravisEz13** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[Assert-HADC.ps1, line 7 \[r1\]](https://reviewable.io:443/reviews/powershell/xactivedirectory/100#-KK_AxJ7bnfDrRYuPgld:-KLTxvqTJm3LQPKbxhjZ:962770003) ([raw file](https://github.com/powershell/xactivedirectory/blob/b6db46aad1ab0df8ab2b31ccb242a70b2151a221/Assert-HADC.ps1#L7)):*
<details><summary><i>Previously, TravisEz13 (Travis Plunk) wrote…</i></summary>
> Are these test files?  If so ,why are they not in the test folder?
</details>
*ping*

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xactivedirectory/100)*

**Comment by PlagueHO** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[Assert-HADC.ps1, line 7 \[r1\]](https://reviewable.io:443/reviews/powershell/xactivedirectory/100#-KK_AxJ7bnfDrRYuPgld:-KK_XjROngZ051oEiOC7:873961189) ([raw file](https://github.com/powershell/xactivedirectory/blob/b6db46aad1ab0df8ab2b31ccb242a70b2151a221/Assert-HADC.ps1#L7)):*
<details><summary><i>Previously, TravisEz13 (Travis Plunk) wrote…</i></summary>
> Are these test files?  If so ,why are they not in the test folder?
</details>
I'm not sure - they do look like manual integration test. @iainbrighton - are the files Assert-HDAC.ps1 and Assert-ParentChildDomains.ps1 for executing manual integration tests? If so, can we move them to the Tests folder as @TravisEz13 suggests?

---

*[DSCResources/MSFT_xADComputer/MSFT_xADComputer.schema.mof, line 16 \[r1\]](https://reviewable.io:443/reviews/powershell/xactivedirectory/100#-KK_BcAsIBYcVY7B0CV5:-KK_YYSIwIzihYb0EOWH:-369106949) ([raw file](https://github.com/powershell/xactivedirectory/blob/b6db46aad1ab0df8ab2b31ccb242a70b2151a221/DSCResources/MSFT_xADComputer/MSFT_xADComputer.schema.mof#L16)):*
<details><summary><i>Previously, TravisEz13 (Travis Plunk) wrote…</i></summary>
> We should reconsider this name.
</details>
I have changed it to RequestFile.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xactivedirectory/100)*

**Comment by iainbrighton** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[Assert-HADC.ps1, line 7 \[r1\]](https://reviewable.io:443/reviews/powershell/xactivedirectory/100#-KK_AxJ7bnfDrRYuPgld:-KLVoYhmghTeIc2D_Gqu:-404618374) ([raw file](https://github.com/powershell/xactivedirectory/blob/b6db46aad1ab0df8ab2b31ccb242a70b2151a221/Assert-HADC.ps1#L7)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary>
> I'm not sure - they do look like manual integration test. @iainbrighton - are the files Assert-HDAC.ps1 and Assert-ParentChildDomains.ps1 for executing manual integration tests? If so, can we move them to the Tests folder as @TravisEz13 suggests?
</details>
@PlagueHO - I'm not sure where these files came from; they were here before my time! I'm happy for them to be moved, but I have no idea who or what might be affected as a result.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xactivedirectory/100)*

**Comment by TravisEz13** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[Assert-HADC.ps1, line 7 \[r1\]](https://reviewable.io:443/reviews/powershell/xactivedirectory/100#-KK_AxJ7bnfDrRYuPgld:-KL_2wlG2ysU5Mk7NgpG:177172760) ([raw file](https://github.com/powershell/xactivedirectory/blob/b6db46aad1ab0df8ab2b31ccb242a70b2151a221/Assert-HADC.ps1#L7)):*
<details><summary><i>Previously, iainbrighton (Iain Brighton) wrote…</i></summary>
> @PlagueHO - I'm not sure where these files came from; they were here before my time! I'm happy for them to be moved, but I have no idea who or what might be affected as a result.
</details>
Can we file an issue to investigate and deal with it?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xactivedirectory/100)*

**Comment by TravisEz13** [comment]
Reviewed 4 of 4 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xactivedirectory/100)*

**Pull request merged**
