### PR TITLE
Adding DatabasePath, LogPath, SysvolPath properties to xADDomain. Closes #21

### LINKED ISSUE #21: Version 2.4 in the PSGallery dropped properties on xADDomain
xActiveDirectory version 2.4 in the PSGallery dropped properties on xADDomain:
DatabasePath
LogPath
Must add these back to the latest version.

### PR DESCRIPTION
**Pull request by GoateePFE**
Replacing code from v2.3 with the additional parameters for xADDomain.

### CODE REVIEW

**Comment by KarolKaczmarek** [comment]
Thanks @GoateePFE ,
Some of the common tests failed though: https://ci.appveyor.com/project/PowerShell/xactivedirectory/build/1.0.51 

Looks like there are tabs instead of spaces in MSFT_xADDomain.psm1 file.
You can fix it by using one of our fixers:
```
Get-TextFilesList $pwd | ConvertTo-SPaceIndentation
```
from here:
https://github.com/powershell/dscresource.tests

Once it's done, please send those changes as another commit to this branch.
Thanks!

**Comment by GoateePFE** [comment]
I removed the one tab from the file.  Please try to test and merge again.

**Comment by GoateePFE** [comment]
Hello Karol,

This has been fixed.  Please retry.  Also, the patch-2 version of this file should be deleted as it is out of date significantly.

Thanks,
Ashley

**Comment by KarolKaczmarek** [comment]
Tests are being run automatically by AppVeyor every time you add commit to the Pull Request.
You can see the current status at the bottom:
```
Some checks have failed — AppVeyor was unable to build non-mergeable pull request  

We can’t automatically merge this pull request. 

Use the command line to resolve conflicts before continuing. 
```

However, as you can see there are some conflicts between your change and existing codebase which prevent tests from being run.

You can find instructions on how to resolve it here: http://githowto.com/resolving_conflicts 
You should merge with dev branch and not master (as in the example from that link) though.


Having said that, I assume conflicts are caused because of merging previous PR: #16 which also modifies MSFT_xADDomain.psm1.
I briefly took a look at it and changes look very similar to what you are committing here. Can you please review them and see if we still want to add anything from this PR?

Thanks!

**Comment by GoateePFE** [comment]
Deferring to Sergei's PR#9 changes that should fix this.

**Pull request closed without merging**
