### PR TITLE
Fix missing Ensure field/read in MOF definition of xADDomainControler

### PR DESCRIPTION
**Pull request by BrunoReboul**
@TravisEz13, linked to #52  
If not fixed then Get-dsccompliance breaks, with error events 4097 and 4252 in operational log
Tested
Have a great day

---

This change is [Reviewable](https://reviewable.io/reviews/powershell/xactivedirectory/111)

### CODE REVIEW

**Comment by BrunoReboul** [comment]
Indentation fixed in mof file

**Comment by BerheAbrha** [comment]
@BrunoReboul your fix looks good. Could you also add test(s) to validate Get-DSCConfiguration works after your fix. Thanks!

**Comment by claudiospizzi** [comment]
The issue still exists, so the Get-DscConfiguration command fails on my domain controllers. Any progress here?

**Comment by Merto410** [comment]
I have this licked.  It needs to be in the schema as you have done and once it's in the schema, get, set, and test have to reference the parameter.  I am submitting a pull request to add the global catalog option per someone's request and it also has this fix.

**Comment by existancenext** [comment]
Where is this issue at?

**Comment by johlju** [comment]
@BrunoReboul Sorry for the long delay in reviewing this PR. Could you please rebase this PR (using `git rebase`) to resolve the merge conflicts?

**Comment by johlju** [comment]
This is also being worked on in #135 either PR can be merged.

**Comment by johlju** [comment]
Labeling as abandoned since it has gone 14 days until last update. An abandoned PR can be continued by another contributor. The abandoned label will be removed if work on the PR is taken up again.

**Comment by johlju** [comment]
Closing this PR as this has been merged by a recent PR.

**Pull request closed without merging**
