### PR TITLE
Mods to xWaitForADDomain

### PR DESCRIPTION
**Pull request by JeffBow**
Made passing of explicit credentials optional and also added a terminate parameter that when set to false will pass a reboot to LCM instead of throwing the not found exception.  I have found the system doesn't recognize environment changes while it is in the retry loop and a reboot without termination will allow it to continue.  I Also changed the discovery method to use [System.DirectoryServices.ActiveDirectory.DomainController]::FindOne   Like the latest branch it doesn't require ADDS Tools but returns a result 10-15 seconds quicker.

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xactivedirectory/88)

### CODE REVIEW

**Comment by TravisEz13** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[DSCResources/MSFT_xWaitForADDomain/MSFT_xWaitForADDomain.psm1, line 2 \[r2\]](https://reviewable.io:443/reviews/powershell/xactivedirectory/88#-KFM2GavrI8kh0phJwO-:-KFM2GawbI2P1_zFISBt:1146265129) ([raw file](https://github.com/powershell/xactivedirectory/blob/f752b0217d1a915ba3367de9de3d405238cf9d67/DSCResources/MSFT_xWaitForADDomain/MSFT_xWaitForADDomain.psm1#L2)):*
Please resolve all merge conflicts.  For more information see [GitHowTo - 30. Resolving Conflicts](http://githowto.com/resolving_conflicts )
[Instructions to setup BC4, my favorite merge tool](http://www.scootersoftware.com/support.php?zz=kb_vcs#gitwindows)

---

*[DSCResources/MSFT_xWaitForADDomain/MSFT_xWaitForADDomain.psm1, line 22 \[r2\]](https://reviewable.io:443/reviews/powershell/xactivedirectory/88#-KFM4imr_WgJ_D0FIvkl:-KFM4imr_WgJ_D0FIvkm:-997639154) ([raw file](https://github.com/powershell/xactivedirectory/blob/f752b0217d1a915ba3367de9de3d405238cf9d67/DSCResources/MSFT_xWaitForADDomain/MSFT_xWaitForADDomain.psm1#L22)):*
Why not just null?

---

*[DSCResources/MSFT_xWaitForADDomain/MSFT_xWaitForADDomain.psm1, line 88 \[r2\]](https://reviewable.io:443/reviews/powershell/xactivedirectory/88#-KFLwR_IwiknHh2Q2ZTb:-KFLwR_IwiknHh2Q2ZTc:-1559118619) ([raw file](https://github.com/powershell/xactivedirectory/blob/f752b0217d1a915ba3367de9de3d405238cf9d67/DSCResources/MSFT_xWaitForADDomain/MSFT_xWaitForADDomain.psm1#L88)):*
This could lead to an infinite reboot loop.

---

*[DSCResources/MSFT_xWaitForADDomain/MSFT_xWaitForADDomain.schema.mof, line 9 \[r2\]](https://reviewable.io:443/reviews/powershell/xactivedirectory/88#-KFLwbyTymguBy9Z-J4n:-KFLwbyTymguBy9Z-J4o:2127475188) ([raw file](https://github.com/powershell/xactivedirectory/blob/f752b0217d1a915ba3367de9de3d405238cf9d67/DSCResources/MSFT_xWaitForADDomain/MSFT_xWaitForADDomain.schema.mof#L9)):*
Files must end with a new line.  See [Style Guidelines, General Rule, #5](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md#general-rules)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xactivedirectory/88)*

**Comment by TravisEz13** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[DSCResources/MSFT_xWaitForADDomain/MSFT_xWaitForADDomain.psm1, line 1 \[r2\]](https://reviewable.io:443/reviews/powershell/xactivedirectory/88#-KFQRsbKZVL6_vON_Yaq:-KFQRsbLBBhZHs5TBaJK:-347034117) ([raw file](https://github.com/powershell/xactivedirectory/blob/f752b0217d1a915ba3367de9de3d405238cf9d67/DSCResources/MSFT_xWaitForADDomain/MSFT_xWaitForADDomain.psm1#L1)):*
[Fix test failure](https://ci.appveyor.com/project/PowerShell/xactivedirectory/build/2.10.170.0)

```
File C:\projects\xactivedirectory\DSCResources\MSFT_xWaitForADDomain\MSFT_xWaitForADDomain.psm1 contains 0x00 bytes. It's probably uses Unicode and need to be converted to UTF-8. Use Fixer 'Get-UnicodeFilesList $pwd | ConvertTo-UTF8'.
    [-] Doesn't use Unicode encoding 5.58s 
      Expected: {0} 
      But was:  {1} 
      120:                 $unicodeFilesCount | Should Be 0 
      at <ScriptBlock>, C:\projects\xactivedirectory\DSCResource.Tests\Meta.Tests.ps1: line 120 
```

---

*[DSCResources/MSFT_xWaitForADDomain/MSFT_xWaitForADDomain.psm1, line 88 \[r2\]](https://reviewable.io:443/reviews/powershell/xactivedirectory/88#-KFLwR_IwiknHh2Q2ZTb:-KFQQMRR_PdCbAiUrQpe:-462739201) ([raw file](https://github.com/powershell/xactivedirectory/blob/f752b0217d1a915ba3367de9de3d405238cf9d67/DSCResources/MSFT_xWaitForADDomain/MSFT_xWaitForADDomain.psm1#L88)):*
Perhaps this should not be the default behavior.  Add an optional Boolean property  to enable rebooting on domain lookup failure.

@iainbrighton Do you have an opinion on this?

---

*[DSCResources/MSFT_xWaitForADDomain/MSFT_xWaitForADDomain.psm1, line 117 \[r2\]](https://reviewable.io:443/reviews/powershell/xactivedirectory/88#-KFQRexIJSywxUdIqsMZ:-KFQRexIJSywxUdIqsM_:-655526974) ([raw file](https://github.com/powershell/xactivedirectory/blob/f752b0217d1a915ba3367de9de3d405238cf9d67/DSCResources/MSFT_xWaitForADDomain/MSFT_xWaitForADDomain.psm1#L117)):*
Fix test failure.
```
   Context Indentations 
There are tab in C:\projects\xactivedirectory\DSCResources\MSFT_xWaitForADDomain\MSFT_xWaitForADDomain.psm1. Use Fixer 'Get-TextFilesList $pwd | ConvertTo-SpaceIndentation'.
    [-] Uses spaces for indentation, not tabs 362ms 
      Expected: {0} 
      But was:  {1} 
      135:                 $totalTabsCount | Should Be 0 
      at <ScriptBlock>, C:\projects\xactivedirectory\DSCResource.Tests\Meta.Tests.ps1: line 135 
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xactivedirectory/88)*

**Comment by iainbrighton** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[DSCResources/MSFT_xWaitForADDomain/MSFT_xWaitForADDomain.psm1, line 88 \[r2\]](https://reviewable.io:443/reviews/powershell/xactivedirectory/88#-KFLwR_IwiknHh2Q2ZTb:-KFccNaqPx1YAdoSBovW:777745771) ([raw file](https://github.com/powershell/xactivedirectory/blob/f752b0217d1a915ba3367de9de3d405238cf9d67/DSCResources/MSFT_xWaitForADDomain/MSFT_xWaitForADDomain.psm1#L88)):*
Would we only ever need a single reboot to "fix" whatever the underlying problem is? If so, could we not write a registry entry when we need to reboot. If the registry entry already exists, we error as we've already attempted a reboot? Obviously we should clear the registry entry after a successful or error run..

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xactivedirectory/88)*

**Comment by JeffBow** [comment]
@iainbrighton   I do not think a single reboot would fix much.  This configurable reboot cycle lets the machine reset completely from a network and name resolver perspective.  It can also keep the LCM alive if the retry count on the normal check is exceeded - meaning the machine has to wait for the default ConfigurationModeFrequencyMins value of 15 minutes before it tries again.  I've found it valuable to be able to force this in Azure provisioing when you have dependent resources or other extensions waiting on the DSC VM Extension

**Comment by TravisEz13** [comment]
Reviewed 1 of 2 files at r4.
Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[DSCResources/MSFT_xWaitForADDomain/MSFT_xWaitForADDomain.psm1, line 9 \[r2\]](https://reviewable.io:443/reviews/powershell/xactivedirectory/88#-KFwXlG41S7tpZrhlKLv:-KFwXlG41S7tpZrhlKLw:481689525) ([raw file](https://github.com/powershell/xactivedirectory/blob/f752b0217d1a915ba3367de9de3d405238cf9d67/DSCResources/MSFT_xWaitForADDomain/MSFT_xWaitForADDomain.psm1#L9)):*
looks like there is a bug in the test that doesn't recognize Mandatory=$false.  My recommendation​ is to remove the attribute and  file a bug in xDscResourceDesigner to fix the test.  I can probably fix it fairly quickly, but it won't take effect for the module until the next release.

---

*[DSCResources/MSFT_xWaitForADDomain/MSFT_xWaitForADDomain.psm1, line 119 \[r2\]](https://reviewable.io:443/reviews/powershell/xactivedirectory/88#-KFwYBOXLeX_KYWukqPi:-KFwYBOXLeX_KYWukqPj:1947731347) ([raw file](https://github.com/powershell/xactivedirectory/blob/f752b0217d1a915ba3367de9de3d405238cf9d67/DSCResources/MSFT_xWaitForADDomain/MSFT_xWaitForADDomain.psm1#L119)):*
Fix tests failure for cmdlet get-domain not found

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xactivedirectory/88)*

**Comment by TravisEz13** [comment]
Reviewed 1 of 2 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xactivedirectory/88)*

**Comment by JeffBow** [comment]
Review status: 1 of 2 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[DSCResources/MSFT_xWaitForADDomain/MSFT_xWaitForADDomain.psm1, line 9 \[r2\]](https://reviewable.io:443/reviews/powershell/xactivedirectory/88#-KFwXlG41S7tpZrhlKLv:-KGFA_pvFMxOnImMVFZh:-264185170) ([raw file](https://github.com/powershell/xactivedirectory/blob/f752b0217d1a915ba3367de9de3d405238cf9d67/DSCResources/MSFT_xWaitForADDomain/MSFT_xWaitForADDomain.psm1#L9)):*
Done.  Removed parameter setting and filed issue with xDscResource

---

*[DSCResources/MSFT_xWaitForADDomain/MSFT_xWaitForADDomain.psm1, line 88 \[r2\]](https://reviewable.io:443/reviews/powershell/xactivedirectory/88#-KFLwR_IwiknHh2Q2ZTb:-KGF9WRlA6bMzv8_Q-tS:1689579977) ([raw file](https://github.com/powershell/xactivedirectory/blob/f752b0217d1a915ba3367de9de3d405238cf9d67/DSCResources/MSFT_xWaitForADDomain/MSFT_xWaitForADDomain.psm1#L88)):*
Done.  Added RebootRetryCount that tracks total reboots in a tmp file.

---

*[DSCResources/MSFT_xWaitForADDomain/MSFT_xWaitForADDomain.psm1, line 119 \[r2\]](https://reviewable.io:443/reviews/powershell/xactivedirectory/88#-KFwYBOXLeX_KYWukqPi:-KGFAMACSLeiydoT8b-K:36830878) ([raw file](https://github.com/powershell/xactivedirectory/blob/f752b0217d1a915ba3367de9de3d405238cf9d67/DSCResources/MSFT_xWaitForADDomain/MSFT_xWaitForADDomain.psm1#L119)):*
Done.  Moved domain test to Get-Domain function

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xactivedirectory/88)*

**Comment by TravisEz13** [comment]
Review status: 1 of 2 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[DSCResources/MSFT_xWaitForADDomain/MSFT_xWaitForADDomain.schema.mof, line 5 \[r5\]](https://reviewable.io:443/reviews/powershell/xactivedirectory/88#-KGFl4PZCJylBPp_5asl:-KGFl4PZCJylBPp_5asm:1478415566) ([raw file](https://github.com/powershell/xactivedirectory/blob/236dfb38aec966e6f5eebaf04ee36ad600ad37f8/DSCResources/MSFT_xWaitForADDomain/MSFT_xWaitForADDomain.schema.mof#L5)):*
Sorry I didn't notice this,  DomainUserCredential must be either Required or Write.  I assumed you intended to change it to Write.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xactivedirectory/88)*

**Comment by TravisEz13** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xactivedirectory/88)*

**Comment by JeffBow** [comment]
Review status: 1 of 2 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[DSCResources/MSFT_xWaitForADDomain/MSFT_xWaitForADDomain.schema.mof, line 5 \[r5\]](https://reviewable.io:443/reviews/powershell/xactivedirectory/88#-KGFl4PZCJylBPp_5asl:-KGFtkqVtgwsVtR3QrJa:-2002456125) ([raw file](https://github.com/powershell/xactivedirectory/blob/236dfb38aec966e6f5eebaf04ee36ad600ad37f8/DSCResources/MSFT_xWaitForADDomain/MSFT_xWaitForADDomain.schema.mof#L5)):*
Done.  Made DomainUserCredential [WRITE]

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xactivedirectory/88)*

**Comment by JeffBow** [comment]
Obviously more work to do on the .test....

**Comment by iainbrighton** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[DSCResources/MSFT_xWaitForADDomain/MSFT_xWaitForADDomain.psm1, line 88 \[r2\]](https://reviewable.io:443/reviews/powershell/xactivedirectory/88#-KFLwR_IwiknHh2Q2ZTb:-KGMRzmUzzVSnSFwhBrk:-1174416612) ([raw file](https://github.com/powershell/xactivedirectory/blob/f752b0217d1a915ba3367de9de3d405238cf9d67/DSCResources/MSFT_xWaitForADDomain/MSFT_xWaitForADDomain.psm1#L88)):*
Do we need both RebootRetryCount and RebootIfDomainNotFound? If RebootRetryCount was not specified (or defaulted to 0) then we wouldn't reboot. If a non-zero value is specified, then we're indicating that we want to reboot?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xactivedirectory/88)*

**Comment by TravisEz13** [comment]
Reviewed 2 of 2 files at r8.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[DSCResources/MSFT_xWaitForADDomain/MSFT_xWaitForADDomain.psm1, line 94 \[r8\]](https://reviewable.io:443/reviews/powershell/xactivedirectory/88#-KGPDMX86ehZBpJJJU6k:-KGPDMX984ASS0Kr5iyx:294209415) ([raw file](https://github.com/powershell/xactivedirectory/blob/1190e5b5171fe1d26aff5f4529d63921d4c1916a/DSCResources/MSFT_xWaitForADDomain/MSFT_xWaitForADDomain.psm1#L94)):*
You should add a test to verify we get to this point with the proper parameters and update the rest to make sure they don't mistakenly set this variable.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xactivedirectory/88)*

**Comment by TravisEz13** [comment]
Reviewed 1 of 1 files at r9.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xactivedirectory/88)*

**Pull request merged**
