### PR TITLE
xADUser: Adds 'Negotiate' option when testing passwords for ADCS integration

### LINKED ISSUE #61: xADUser error if personal Client Authentication intent certificate exists
xADUser fails with the following error if a Personal certificate exists with 'Client Authentication' intent

```
PowerShell DSC resource MSFT_xADUser  failed to execute Test-TargetResource functionality with error message: Exception calling "ValidateCredentials" with "2" argument(s): "The server cannot handle directory requests."
```

Error occurs in latest dev and master branches.

The certificate is being used to encrypt credentials in a DSC push configuration but even if .mof files are set to contain plain text passwords the error still occurs.
Disabling the certificate in mmc -> Certificates stops error from occurring.

Software versions identical both servers:
* **OS**                                          Windows Server 2012 R2                                                                                                                                                                                                                 
* **PSVersion**                               5.0.10514.6                                                                                                                                                                                                                      
* **WSManStackVersion**              3.0                                                                                                                                                                                                                              
* **SerializationVersion**                1.1.0.1                                                                                                                                                                                                                          
* **CLRVersion**                            4.0.30319.42000                                                                                                                                                                                                                  
* **BuildVersion**                           10.0.10514.6                                                                                                                                                                                                                     
* **PSCompatibleVersions**           {1.0, 2.0, 3.0, 4.0...}                                                                                                                                                                                                          
* **PSRemotingProtocolVersion**   2.3   

**Potential fix**
After discovering an article (see below) and a lot of trial and error I appear to have been able to fix the issue by adding the 3rd optional parameter of ValidateCredentials set to [DirectoryServices.AccountManagement.ContextOptions]::SimpleBind
```
$result = $prnContext.ValidateCredentials($UserName, $Password.GetNetworkCredential().Password, [DirectoryServices.AccountManagement.ContextOptions]::SimpleBind)
```

Article: http://forums.asp.net/t/1621077.aspx

### PR DESCRIPTION
**Pull request by iainbrighton**
* Adds 'Negotiate' option when testing user passwords to support Active Directory Certificate Services integration
* Adds descriptions to parameters
* Adds descriptions to MSFT_xADUser.schema.mof
* Updates readme
* Fixes #61

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xactivedirectory/97)

### CODE REVIEW

**Comment by TravisEz13** [comment]
Reviewed 1 of 2 files at r1, 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[DSCResources/MSFT_xADUser/MSFT_xADUser.psm1, line 976 \[r2\]](https://reviewable.io:443/reviews/powershell/xactivedirectory/97#-KIjOAEUiGqCHCKb_iQX:-KIjOAEVv7jU-oktO7UO:1472575046) ([raw file](https://github.com/powershell/xactivedirectory/blob/14734877afa2f61df643ef7c5d1605bd3d48d170/DSCResources/MSFT_xADUser/MSFT_xADUser.psm1#L976)):*
> ```PowerShell
>         $UserName,
>         $Password.GetNetworkCredential().Password,
>         [System.DirectoryServices.AccountManagement.ContextOptions]::Negotiate
> ```

technically this is a downgrade of security, perhaps this should be a property?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xactivedirectory/97)*

**Comment by iainbrighton** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[DSCResources/MSFT_xADUser/MSFT_xADUser.psm1, line 976 \[r2\]](https://reviewable.io:443/reviews/powershell/xactivedirectory/97#-KIjOAEUiGqCHCKb_iQX:-KJ5YMzNlkkJNoNx3dXA:-858683364) ([raw file](https://github.com/powershell/xactivedirectory/blob/14734877afa2f61df643ef7c5d1605bd3d48d170/DSCResources/MSFT_xADUser/MSFT_xADUser.psm1#L976)):*
<details><summary><i>Previously, TravisEz13 (Travis Plunk) wrote…</i></summary>
> technically this is a downgrade of security, perhaps this should be a property?
</details>
It appears the default value is `ContextOptions.Negotiate | ContextOptions.Signing | ContextOptions.Sealing`. Looking at the [documentation](https://msdn.microsoft.com/en-us/library/system.directoryservices.accountmanagement.contextoptions(v=vs.110).aspx), it appears that `ContextOptions.SecureSocketLayer` needs to be added to support ADCS. However, I think this will break authentication when ADCS is not deployed.

I'll perform some checks locally and implement an `UseSSL` parameter if required. I'm not sure why `ContextOptions.Negotiate` would have worked on its own (with ADCS deployed) and `ContextOptions.SecureSocketLayer` not specified?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xactivedirectory/97)*

**Comment by TravisEz13** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[DSCResources/MSFT_xADUser/MSFT_xADUser.psm1, line 976 \[r2\]](https://reviewable.io:443/reviews/powershell/xactivedirectory/97#-KIjOAEUiGqCHCKb_iQX:-KJgQhCu5SFNcOLjT6dx:1140033701) ([raw file](https://github.com/powershell/xactivedirectory/blob/14734877afa2f61df643ef7c5d1605bd3d48d170/DSCResources/MSFT_xADUser/MSFT_xADUser.psm1#L976)):*
<details><summary><i>Previously, iainbrighton (Iain Brighton) wrote…</i></summary>
> Right - riddle me this, Batman. I've installed ADCS in a single DC domain. When attempting to set user passwords with the xADUser resource and ADCS installed,
> 
> Here's the original call to `ValidateCredentials` where I do get the errors this PR is supposed to fix:
> ```Powershell
> return $principalContext.ValidateCredentials(
>     $UserName,
>     $Password.GetNetworkCredential().Password
> );
> ```
> Here's the output:
> ```powershell
> VERBOSE: [CONTROLLER]: LCM:  [ Start  Test     ]  [[xADUser]Iainbrighton]
> VERBOSE: [CONTROLLER]:                            [[xADUser]Iainbrighton] Importing the module MSFT_xADUser in force mode.
> VERBOSE: [CONTROLLER]:                            [[xADUser]Iainbrighton] Retrieving Active Directory user 'IainBrighton' (IainBrighton@lab.local) ...
> VERBOSE: [CONTROLLER]:                            [[xADUser]Iainbrighton] Active Directory user 'IainBrighton' (IainBrighton@lab.local) is present.
> VERBOSE: [CONTROLLER]:                            [[xADUser]Iainbrighton] Creating connection to Active Directory domain 'lab.local' ...
> VERBOSE: [CONTROLLER]:                            [[xADUser]Iainbrighton] Checking Active Directory user 'IainBrighton' password ...
> Exception calling "ValidateCredentials" with "2" argument(s): "The server cannot handle directory requests."
>     + CategoryInfo          : NotSpecified: (:) [], CimException
>     + FullyQualifiedErrorId : DirectoryOperationException
>     + PSComputerName        : localhost
> VERBOSE: [CONTROLLER]:                            [[xADUser]Iainbrighton] User 'Password' property is NOT in the desired state. Expected '<Password>', actual '<Password>'.
> VERBOSE: [CONTROLLER]: LCM:  [ End    Test     ]  [[xADUser]Iainbrighton]  in 3.3740 seconds.
> ```
> If I add just the `Negotiate` option:
> ```powershell
> return $principalContext.ValidateCredentials(
>     $UserName,
>     $Password.GetNetworkCredential().Password,
>     [System.DirectoryServices.AccountManagement.ContextOptions]::Negotiate 
> );
> ```
> And run this, it does work, but is potentially less secure:
> ```powershell
> VERBOSE: [CONTROLLER]: LCM:  [ Start  Test     ]  [[xADUser]Iainbrighton]
> VERBOSE: [CONTROLLER]:                            [[xADUser]Iainbrighton] Importing the module MSFT_xADUser in force mode.
> VERBOSE: [CONTROLLER]:                            [[xADUser]Iainbrighton] Retrieving Active Directory user 'IainBrighton' (IainBrighton@lab.local) ...
> VERBOSE: [CONTROLLER]:                            [[xADUser]Iainbrighton] Active Directory user 'IainBrighton' (IainBrighton@lab.local) is present.
> VERBOSE: [CONTROLLER]:                            [[xADUser]Iainbrighton] Creating connection to Active Directory domain 'lab.local' ...
> VERBOSE: [CONTROLLER]:                            [[xADUser]Iainbrighton] Checking Active Directory user 'IainBrighton' password ...
> VERBOSE: [CONTROLLER]: LCM:  [ End    Test     ]  [[xADUser]Iainbrighton]  in 2.4220 seconds.
> ```
> Now - if I add the "default" context options (as per the documentation):
> ```powershell
> return $principalContext.ValidateCredentials(
>     $UserName,
>     $Password.GetNetworkCredential().Password,
>     [System.DirectoryServices.AccountManagement.ContextOptions]::Negotiate -bor
>         [System.DirectoryServices.AccountManagement.ContextOptions]::Signing -bor
>             [System.DirectoryServices.AccountManagement.ContextOptions]::Sealing
> );
> ```
> And run the configuration:
> ```powershell
> VERBOSE: [CONTROLLER]: LCM:  [ Start  Test     ]  [[xADUser]Iainbrighton]
> VERBOSE: [CONTROLLER]:                            [[xADUser]Iainbrighton] Importing the module MSFT_xADUser in force mode.
> VERBOSE: [CONTROLLER]:                            [[xADUser]Iainbrighton] Retrieving Active Directory user 'IainBrighton' (IainBrighton@lab.local) ...
> VERBOSE: [CONTROLLER]:                            [[xADUser]Iainbrighton] Active Directory user 'IainBrighton' (IainBrighton@lab.local) is present.
> VERBOSE: [CONTROLLER]:                            [[xADUser]Iainbrighton] Creating connection to Active Directory domain 'lab.local' ...
> VERBOSE: [CONTROLLER]:                            [[xADUser]Iainbrighton] Checking Active Directory user 'IainBrighton' password ...
> VERBOSE: [CONTROLLER]: LCM:  [ End    Test     ]  [[xADUser]Iainbrighton]  in 2.2500 seconds.
> VERBOSE: [CONTROLLER]: LCM:  [ Skip   Set      ]  [[xADUser]Iainbrighton]
> ```
> It works?! Aren't these supposed to be the defaults anyway that should be used in the first (and existing) example?! Confused!
</details>
Let's discuss offline

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xactivedirectory/97)*

**Comment by TravisEz13** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[DSCResources/MSFT_xADUser/MSFT_xADUser.psm1, line 973 \[r2\]](https://reviewable.io:443/reviews/powershell/xactivedirectory/97#-KJgQplFxtpRdXMhe99l:-KJgQplFxtpRdXMhe99m:-2020607900) ([raw file](https://github.com/powershell/xactivedirectory/blob/14734877afa2f61df643ef7c5d1605bd3d48d170/DSCResources/MSFT_xADUser/MSFT_xADUser.psm1#L973)):*
> ```PowerShell
>     }
>     Write-Verbose -Message ($LocalizedData.CheckingADUserPassword -f $UserName);
>     return $principalContext.ValidateCredentials(
> ```

Merge conflicts must be resolved.

---

*[DSCResources/MSFT_xADUser/MSFT_xADUser.psm1, line 976 \[r2\]](https://reviewable.io:443/reviews/powershell/xactivedirectory/97#-KIjOAEUiGqCHCKb_iQX:-KJgU2Yg_W9W-9mwmENg:295059162) ([raw file](https://github.com/powershell/xactivedirectory/blob/14734877afa2f61df643ef7c5d1605bd3d48d170/DSCResources/MSFT_xADUser/MSFT_xADUser.psm1#L976)):*
<details><summary><i>Previously, TravisEz13 (Travis Plunk) wrote…</i></summary>
> Let's discuss offline
</details>
I suspect this is not the default:

      [System.DirectoryServices.AccountManagement.ContextOptions]::Negotiate -bor
         [System.DirectoryServices.AccountManagement.ContextOptions]::Signing -bor
             [System.DirectoryServices.AccountManagement.ContextOptions]::Sealing

 but this is

         [System.DirectoryServices.AccountManagement.ContextOptions]::Signing -bor
             [System.DirectoryServices.AccountManagement.ContextOptions]::Sealing

But,​ I cannot find doc's I believe.  What I am more sure of is that negotiate is not part of the default.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xactivedirectory/97)*

**Comment by iainbrighton** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[DSCResources/MSFT_xADUser/MSFT_xADUser.psm1, line 976 \[r2\]](https://reviewable.io:443/reviews/powershell/xactivedirectory/97#-KIjOAEUiGqCHCKb_iQX:-KJqyWPqffuxDE-QT9Af:188739042) ([raw file](https://github.com/powershell/xactivedirectory/blob/14734877afa2f61df643ef7c5d1605bd3d48d170/DSCResources/MSFT_xADUser/MSFT_xADUser.psm1#L976)):*
<details><summary><i>Previously, TravisEz13 (Travis Plunk) wrote…</i></summary>
> I suspect this is not the default:
> 
>       [System.DirectoryServices.AccountManagement.ContextOptions]::Negotiate -bor
>          [System.DirectoryServices.AccountManagement.ContextOptions]::Signing -bor
>              [System.DirectoryServices.AccountManagement.ContextOptions]::Sealing
> 
>  but this is
> 
>          [System.DirectoryServices.AccountManagement.ContextOptions]::Signing -bor
>              [System.DirectoryServices.AccountManagement.ContextOptions]::Sealing
> 
> But,​ I cannot find doc's I believe.  What I am more sure of is that negotiate is not part of the default.
</details>
I've added a 'PassswordAuthenticationContext' parameter. Not setting this or setting it to 'Default' is as we were. To drop to NTLM authentication, you'll need to explicitly set the parameter to 'Negotiate'.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xactivedirectory/97)*

**Comment by iainbrighton** [comment]
@TravisEz13 @KarolKaczmarek Have the PSSA checks been changed recently? Do I need to now fix those PSSA errors in the example files? If so, is PSSA v1.6 now being used so I can suppress the rules in the example configurations?

**Comment by TravisEz13** [comment]
Reviewed 4 of 4 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[DSCResources/MSFT_xADUser/MSFT_xADUser.psm1, line 973 \[r2\]](https://reviewable.io:443/reviews/powershell/xactivedirectory/97#-KJgQplFxtpRdXMhe99l:-KJv_hYfNFgBjzJzD0k6:1830604248) ([raw file](https://github.com/powershell/xactivedirectory/blob/14734877afa2f61df643ef7c5d1605bd3d48d170/DSCResources/MSFT_xADUser/MSFT_xADUser.psm1#L973)):*
<details><summary><i>Previously, TravisEz13 (Travis Plunk) wrote…</i></summary>
> Merge conflicts must be resolved.
</details>
builds are failing now

---

*[DSCResources/MSFT_xADUser/MSFT_xADUser.schema.mof, line 48 \[r3\]](https://reviewable.io:443/reviews/powershell/xactivedirectory/97#-KJva-9KZtfIRuNXGtdz:-KJva-9KZtfIRuNXGte-:1167946405) ([raw file](https://github.com/powershell/xactivedirectory/blob/b85849dd6714e44ec4d500f018dab3e3affb73af/DSCResources/MSFT_xADUser/MSFT_xADUser.schema.mof#L48)):*
> ```
>     [Write, Description("Specifies the Active Directory Domain Services instance to use to perform the task.")] String DomainController;
>     [Write, Description("Specifies the user account credentials to use to perform this task"), EmbeddedInstance("MSFT_Credential")] String DomainAdministratorCredential;
>     [Write, Description("Specifies the authentication context type used when testing passwords"), ValueMap{"Default","Negotiate"},Values{"Default","Negotiate"}] String PasswordAuthenticationContext;
> ```

New-PSSession and most CmdLets I see just call this Authentication

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xactivedirectory/97)*

**Comment by iainbrighton** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[DSCResources/MSFT_xADUser/MSFT_xADUser.psm1, line 973 \[r2\]](https://reviewable.io:443/reviews/powershell/xactivedirectory/97#-KJgQplFxtpRdXMhe99l:-KKSiM9Nwf7uxFrDOvBZ:-1405318610) ([raw file](https://github.com/powershell/xactivedirectory/blob/14734877afa2f61df643ef7c5d1605bd3d48d170/DSCResources/MSFT_xADUser/MSFT_xADUser.psm1#L973)):*
<details><summary><i>Previously, TravisEz13 (Travis Plunk) wrote…</i></summary>
> builds are failing now
</details>
Yes - this is due to changes in the PSSA module/build flagging things incorrectly?

---

*[DSCResources/MSFT_xADUser/MSFT_xADUser.schema.mof, line 48 \[r3\]](https://reviewable.io:443/reviews/powershell/xactivedirectory/97#-KJva-9KZtfIRuNXGtdz:-KKShf5VgrhZu7YC54tu:1089645408) ([raw file](https://github.com/powershell/xactivedirectory/blob/b85849dd6714e44ec4d500f018dab3e3affb73af/DSCResources/MSFT_xADUser/MSFT_xADUser.schema.mof#L48)):*
<details><summary><i>Previously, TravisEz13 (Travis Plunk) wrote…</i></summary>
> New-PSSession and most CmdLets I see just call this Authentication
</details>
Agreed. However, using 'Authentication' would imply its the authentication that's used throughout the resource to communicate with AD? Remember, this authentication mechanism is _only_ used if a password is specified for password verification - nothing else.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xactivedirectory/97)*

**Comment by PlagueHO** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[DSCResources/MSFT_xADUser/MSFT_xADUser.psm1, line 973 \[r2\]](https://reviewable.io:443/reviews/powershell/xactivedirectory/97#-KJgQplFxtpRdXMhe99l:-KKSikdQhfj243iJ3J2V:111019373) ([raw file](https://github.com/powershell/xactivedirectory/blob/14734877afa2f61df643ef7c5d1605bd3d48d170/DSCResources/MSFT_xADUser/MSFT_xADUser.psm1#L973)):*
<details><summary><i>Previously, iainbrighton (Iain Brighton) wrote…</i></summary>
> Yes - this is due to changes in the PSSA module/build flagging things incorrectly?
</details>
I've fixed all the PSSA failures in PR #100.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xactivedirectory/97)*

**Comment by TravisEz13** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[DSCResources/MSFT_xADUser/MSFT_xADUser.schema.mof, line 48 \[r3\]](https://reviewable.io:443/reviews/powershell/xactivedirectory/97#-KJva-9KZtfIRuNXGtdz:-KK_F-My60NGjxpSfmTm:-2119226460) ([raw file](https://github.com/powershell/xactivedirectory/blob/b85849dd6714e44ec4d500f018dab3e3affb73af/DSCResources/MSFT_xADUser/MSFT_xADUser.schema.mof#L48)):*
<details><summary><i>Previously, iainbrighton (Iain Brighton) wrote…</i></summary>
> Agreed. However, using 'Authentication' would imply its the authentication that's used throughout the resource to communicate with AD? Remember, this authentication mechanism is _only_ used if a password is specified for password verification - nothing else.
</details>
remove the word context or reorder to PasswordContextAuthentication.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xactivedirectory/97)*

**Comment by iainbrighton** [comment]
Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[DSCResources/MSFT_xADUser/MSFT_xADUser.psm1, line 973 \[r2\]](https://reviewable.io:443/reviews/powershell/xactivedirectory/97#-KJgQplFxtpRdXMhe99l:-KLunXyKUZa6zMh3Vr4O:1736281815) ([raw file](https://github.com/powershell/xactivedirectory/blob/14734877afa2f61df643ef7c5d1605bd3d48d170/DSCResources/MSFT_xADUser/MSFT_xADUser.psm1#L973)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary>
> I've fixed all the PSSA failures in PR #100.
</details>
@PlagueHO - Thanks! I've resolved the merge conflicts and now things are building successfully :+1: 

---

*[DSCResources/MSFT_xADUser/MSFT_xADUser.schema.mof, line 48 \[r3\]](https://reviewable.io:443/reviews/powershell/xactivedirectory/97#-KJva-9KZtfIRuNXGtdz:-KLunhrTdRg4Ff1AhKxI:657530533) ([raw file](https://github.com/powershell/xactivedirectory/blob/b85849dd6714e44ec4d500f018dab3e3affb73af/DSCResources/MSFT_xADUser/MSFT_xADUser.schema.mof#L48)):*
<details><summary><i>Previously, TravisEz13 (Travis Plunk) wrote…</i></summary>
> remove the word context or reorder to PasswordContextAuthentication.
</details>
I've removed 'Context' from the parameter so it's now just `PasswordAuthentication`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xactivedirectory/97)*

**Comment by TravisEz13** [comment]
Reviewed 4 of 4 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xactivedirectory/97)*

**Pull request merged**
