### PR TITLE
xActiveDirectory: Move Resource Descriptions to Wiki

### LINKED ISSUE #289: xActiveDirectory: Move resource module to auto documentation
It would really be good to move this resource to automatic documentation. This would simplify for contributors and maintainers.
This can be an undertaking to get working. Suggest peeking at an existing resource like ComputerManagementDsc that uses this.

Some documentation here:
https://github.com/PowerShell/DscResource.Tests#documentation-helper-module

### PR DESCRIPTION
**Pull request by X-Guardian**
#### Pull Request (PR) description

This PR moves the resource descriptions from the main README to individual README files in each resource subdirectory. This is to enable the DocumentationHelper module to use these to build the Wiki.

#### This Pull Request (PR) fixes the following issues

- Fixes #289

#### Task list

- [x] Added an entry under the Unreleased section in the CHANGELOG.md.
      Entry should say what was changed, and how that affects users (if applicable).
- [x] Resource documentation added/updated in README.md.
- [ ] Resource parameter descriptions added/updated in README.md, schema.mof
      and comment-based help.
- [ ] Comment-based help added/updated.
- [ ] Localization strings added/updated in all localization files as appropriate.
- [ ] Examples appropriately added/updated.
- [ ] Unit tests added/updated. See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [ ] Integration tests added/updated (where possible). See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [ ] New/changed code adheres to [DSC Resource Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md) and [Best Practices](https://github.com/PowerShell/DscResources/blob/master/BestPractices.md).

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xactivedirectory/310)

### CODE REVIEW

**Comment by johlju** [comment]
@PlagueHO could you help me out an review this since your are more familiar with the auto-documentation? Like what should stay in README.md and what should be taken out. Is there anything else that should be added? Thanks 😄

**Comment by X-Guardian** [comment]
Hi @johlju, I pushed the auto-generated pages into the Wiki in my fork, if you want to take a look at them: https://github.com/X-Guardian/xActiveDirectory/wiki

**Comment by johlju** [comment]
@X-Guardian Looking good. 🙂 Seems it auto-doc is not godd with long parameter names. Maybe we should move away from using a table, and format it another way. But out of scope for this PR. 🙂 
https://github.com/X-Guardian/xActiveDirectory/wiki/xADKDSKey

@X-Guardian Wonder if we should have a list of the resources on the README. that link to the Wiki, or at least have something in the README.md telling users where they can find the documentation?
Mayeb something like https://github.com/PowerShell/ComputerManagementDsc#documentation-and-examples?

**Comment by X-Guardian** [comment]
Hi @johlju, I think the main problem is the ultra narrow format of the Github Wiki pages. If you look at the Wiki pages for any of the other DSC modules, the tables all look squashed.

I already added the following section to the README, which mirrors what other DSC modules have:

```
## Documentation and Examples

For a full list of resources in ActiveDirectoryCSDsc and examples on their use, check
out the [xActiveDirectory wiki](https://github.com/PowerShell/xActiveDirectory/wiki).
```

**Comment by johlju** [comment]
> I think the main problem is the ultra narrow format of the Github Wiki pages. If you look at the Wiki pages for any of the other DSC modules, the tables all look squashed.

Yep. My thought were it if was not a table it would wrap better. For example a item list (like was in the README.md). But it just formatting. Everything looks good for this PR. 🙂

**Comment by X-Guardian** [comment]
I was waiting for #309 to be merged, to save having to resolve conflicts on the file.

**Comment by X-Guardian** [comment]
Hmm, Wiki is empty. How are the pages supposed to get there, Manually?

**Comment by johlju** [comment]
Yes apparently that step is manual 😕 I fixed it now. Cloned the wiki and push the changes files.

**Comment by johlju** [comment]
Honestly I thought that would be automatic. It should be able to get to be automatic. I will submit an issue to DscResource.Tests so we can work on that.

**Comment by X-Guardian** [comment]
There is already an issue for this here: 
https://github.com/PowerShell/DscResource.Tests/issues/142

**Pull request merged**
