### PR TITLE
xADObjectEnabledState: New resource 

### PR DESCRIPTION
**Pull request by johlju**
#### Pull Request (PR) description
- Changes to xActiveDirectory
  - Added new resource xADObjectEnabledState. This resource should be
    used to enforce the `Enabled` property of computer accounts. This
    resource replaces the deprecated `Enabled` property in the resource
    xADComputer.

The verbose output of the integration tests are in this gist:
https://gist.github.com/johlju/fdb402beb503529d9265f934e4ec6781

#### This Pull Request (PR) fixes the following issues
From the result of the discussion in PR #170 and fixes one part of the outcome in option #1 in the https://github.com/PowerShell/xActiveDirectory/pull/170#issuecomment-477706305.

#### Task list

- [x] Added an entry under the Unreleased section in the CHANGELOG.md.
      Entry should say what was changed, and how that affects users (if applicable).
- [x] Resource documentation added/updated in README.md.
- [x] Resource parameter descriptions added/updated in README.md, schema.mof
      and comment-based help.
- [x] Comment-based help added/updated.
- [x] Localization strings added/updated in all localization files as appropriate.
- [x] Examples appropriately added/updated.
- [x] Unit tests added/updated. See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [x] Integration tests added/updated (where possible). See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [x] New/changed code adheres to [DSC Resource Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md) and [Best Practices](https://github.com/PowerShell/DscResources/blob/master/BestPractices.md).

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xactivedirectory/277)

### CODE REVIEW

**Comment by johlju** [comment]
@nyanhp, @devopsjesus or @rchristman89 could anyone of you review this PR when you have time? It's a larger PR (new resource).

**Comment by johlju** [comment]
@PlagueHO World you mind review this one when you have a chance. We need to have this merged before next release (~month away) 😊

**Comment by johlju** [comment]
@PlagueHO know your busy. Just pinging for a reminder. 🙂

**Comment by johlju** [comment]
@devopsjesus this one is ready for review again.

**Comment by johlju** [comment]
@devopsjesus do you have time to look through this again, would love to fix any more potential issues so we can get this merged. 🙂

**Comment by devopsjesus** [comment]
I will try to get to this in the next few days :)

**Comment by johlju** [comment]
Thank you! 🙇

**Comment by johlju** [comment]
@devopsjesus thank you so much for the review! 😃 

I will merge this as soon as I have merged in another PR.

**Pull request merged**
