### PR TITLE
xWaitForADDomain: Fix Issue #341

### LINKED ISSUE #341: xWaitForADDomain: This resource is missing comment-based help
This resource is missing comment-based help for the functions.

### PR DESCRIPTION
**Pull request by RobertCGouge**
#### Pull Request (PR) description
This PR addresses issue #341.  It adds comment based help to the xWaitForADDomain resource.

#### This Pull Request (PR) fixes the following issues

-Fixes #341 

#### Task list

- [x] Added an entry under the Unreleased section in the CHANGELOG.md.
      Entry should say what was changed, and how that affects users (if applicable).
- [ ] Resource documentation added/updated in resource directory README.md.
- [x] Resource parameter descriptions added/updated in schema.mof
      and comment-based help.
- [ ] Comment-based help added/updated.
- [x] Localization strings added/updated in all localization files as appropriate.
- [ ] Examples appropriately added/updated.
- [ ] Unit tests added/updated. See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [ ] Integration tests added/updated (where possible). See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [x] New/changed code adheres to [DSC Resource Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md) and [Best Practices](https://github.com/PowerShell/DscResources/blob/master/BestPractices.md).

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xactivedirectory/435)

### CODE REVIEW

**Comment by johlju** [comment]
@RobertCGouge another thing. if you see the comment lines go over ~80 chars, then please line break them around ~80 chars (not a hard limit), it helps when reviewing. Don't think that was an issue in this resource though, but there will be others, as I'm hoping you want to resolve the others issues as well eventually. 😁 
If you use VSCode there is a tool that can be enabled, just add this to your VS Code user settings.
```json
    "editor.rulers": [
        80
    ],
```

**Comment by RobertCGouge** [comment]
Thank you for the guidance.  I have always thought the best practice was to have the help in both places.  I've removed the comments from inside the function and left them in the comment blocks.

**Comment by johlju** [comment]
@RobertCGouge No worries, happy to help out. Looks like the descriptions above the parameters i Get-TargetResource was not removed. 🙂 

Also, when you have resolved the review comments, or if you need to discuss a comment. Could you please go into Reviewable and write 'Done' (or click the done-button) on each of the review comments. This allows me to acknowledge (resolve) the review comments and I know that you are done with each change. After you written 'Done' on each review comment,  or comment on the review comment if it needs further discussion, then click the big green 'Publish' button on top of the page. That will send all your comments back as one big comment to this PR.
You find Reviewable if you click on the big purple Reviewable-button in the PR description. 🙂

**Comment by johlju** [comment]
@RobertCGouge merged! Thank you so much!

**Pull request merged**
