### PR TITLE
xActiveDirectory: Requirements section

### LINKED ISSUE #394: xActiveDirectory: Resource have a requirements section (in wiki README.md)
The resource xADComputer have a _Requirements_ section in the README.md that is used to generate the wiki documentation. See here https://github.com/PowerShell/xActiveDirectory/blob/dev/DSCResources/MSFT_xADComputer/README.md

I suggest we add this section to the other resources README.md as well. The *Requirements*  section is meant to list requirements for a resource, for example if the resource or a specific property can only be used on node with Windows Server 2016 and above, or AD of a specific flavor or specific configuration.

### PR DESCRIPTION
**Pull request by JamesFrierson1**
#### Pull Request (PR) description

Added a Requirements section to every DSCResource README with the bullet point stating "Target machine must be running Windows Server 2008 R2 or later". 

#### This Pull Request (PR) fixes the following issues

Fixes #394 

#### Task list

- [x] Added an entry under the Unreleased section in the CHANGELOG.md.

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xactivedirectory/399)

### CODE REVIEW

**Comment by johlju** [comment]
@JamesFrierson1 Could you please resolve the merge conflicts? It seems your working branch is not using the latest changes merged into the dev branch.

See here how to resolve merge conflicts
https://github.com/PowerShell/DscResources/blob/master/GettingStartedWithGitHub.md#resolve-merge-conflicts

**Comment by johlju** [comment]
*[a discussion](https://reviewable.io/reviews/powershell/xactivedirectory/399#-LiJtdPi7us0VKWF_ku_:-LiJtdPi7us0VKWF_kua:b7t7rzo) (no related file):*
Can you please resolve the failing tests here https://ci.appveyor.com/project/PowerShell/xactivedirectory/builds/25563778?fullLog=true#L307

---

**Comment by johlju** [comment]
@JamesFrierson1 with "Please add an the empty row after this section" i meant after the row (after the section header) 🙂

**Comment by johlju** [comment]
@JamesFrierson1 When you have resolved the review comments, then please go into reviewable and write done on each so I can resolve them. 🙂

**Comment by JamesFrierson1** [comment]
Thank you for your patience, @johlju !  I added the proper spacing per your instructions and updated my changlog entry with a link to the issue

**Comment by johlju** [comment]
@JamesFrierson1 Thank you for this! 😃

**Comment by JamesFrierson1** [comment]
You're very welcome @joeyaiello ! My pleasure 😄

**Pull request merged**
