### PR TITLE
xActiveDirectory: Opt-in to "Common Tests - Validate Localization" and standardise Localization files

### LINKED ISSUE #281: ActiveDirectory: Enable the tests "Common Tests - Validate Localization"
To help contributors and maintainers we should enable the common test "Common Tests - Validate Localization".

### PR DESCRIPTION
**Pull request by X-Guardian**
#### Pull Request (PR) description

This PR opts-in to the "Common Tests - Validate Localization" DSC Resource test and standardises the localisation files and common module loading across all the resources.

Summary of changes:

- Move localized data to external file in the following modules:
  - MSFT_xADCommon
  - MSFT_xADDomain
  - MSFT_xADDomainDefaultPasswordPolicy
  - MSFT_xADGroup
  - MSFT_xADOrganizationalUnit
  - MSFT_xADUser
- Align localized data in the following modules:
  - MSFT_xADComputer.strings
  - MSFT_xADDomainController.strings
  - MSFT_xADForestProperties
  - MSFT_xADKDSKey
  - MSFT_xADReplicationSiteLink
- Comment out unused localized data in the following modules:
  - MSFT_xADCommon
  - MSFT_xADDomain
  - MSFT_xADDomainController
  - MSFT_xADDomainDefaultPasswordPolicy
  - MSFT_xADGroup
  - MSFT_xADManagedServiceAccount
  - MSFT_xADOrganizationalUnit
  - MSFT_xADUser
- Standardise Common Module loading code in the following modules:
  - MSFT_xADDomain
  - MSFT_xADDomainDefaultPasswordPolicy
  - MSFT_xADForestProperties
  - MSFT_xADGroup
  - MSFT_xADKDSKey
  - MSFT_xADManagedServiceAccount
  - MSFT_xADObjectPermissionEntry
  - MSFT_xADOrganizationalUnit
  - MSFT_xADUser

#### This Pull Request (PR) fixes the following issues

- Fixes #281

#### Task list

- [x] Added an entry under the Unreleased section in the CHANGELOG.md.
      Entry should say what was changed, and how that affects users (if applicable).
- [ ] Resource documentation added/updated in README.md.
- [ ] Resource parameter descriptions added/updated in README.md, schema.mof
      and comment-based help.
- [ ] Comment-based help added/updated.
- [x] Localization strings added/updated in all localization files as appropriate.
- [ ] Examples appropriately added/updated.
- [ ] Unit tests added/updated. See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [ ] Integration tests added/updated (where possible). See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [ ] New/changed code adheres to [DSC Resource Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md) and [Best Practices](https://github.com/PowerShell/DscResources/blob/master/BestPractices.md).

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xactivedirectory/307)

### CODE REVIEW

**Comment by johlju** [comment]
Wow! This is really massive work! Thank you! 😃 🙇  Might not have time to review today, but will get on this as soon as possible.

**Comment by X-Guardian** [comment]
No problem @johlju. All ready apart from the CHANGELOG, as I can't decide how much detail to add it to from this. Thoughts?

**Comment by johlju** [comment]
I'm okay with just adding one entry under 'Changes to xActiveDirectory' saying 'Added localization to all resources' or something like that.

**Comment by johlju** [comment]
I will merge in another PR as soon as the tests passes. So if you wait a few minutes to rebase you get that one in too. 🙂

**Pull request merged**
