### PR TITLE
xADDomainController: Fix Issue #155 - Get-TargetResource fails

### LINKED ISSUE #155: xADDomainController: Get-DscConfiguration fails
The PowerShell DSC resource  returned results that are not valid from Get-TargetResource. The Ensure key is not a valid property in the corresponding DSC resource schema file. The results from Get-TargetResource 
must be in a Hashtable format. The keys in the Hashtable must be the same as the properties in the corresponding DSC resource schema file.

### PR DESCRIPTION
**Pull request by devopsjesus**
#### Pull Request (PR) description
Added a read property (Ensure) to the xADDomainController resource
This required making a variety of edits to the Tests file to have them run outside a deployed Domain Controller

#### This Pull Request (PR) fixes the following issues
- Fixes #155 

#### Task list
- [x] Added an entry under the Unreleased section of the change log in the README.md.
      Entry should say what was changed, and how that affects users (if applicable).
- [x] Resource documentation added/updated in README.md.
- [x] Resource parameter descriptions added/updated in README.md, schema.mof
      and comment-based help.
- [ ] Comment-based help added/updated.
- [ ] Localization strings added/updated in all localization files as appropriate.
- [ ] Examples appropriately added/updated.
- [X] Unit tests added/updated. See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [ ] Integration tests added/updated (where possible). See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [X] New/changed code adheres to [DSC Resource Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md) and [Best Practices](https://github.com/PowerShell/DscResources/blob/master/BestPractices.md).

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xactivedirectory/249)

### CODE REVIEW

**Comment by johlju** [comment]
I just merged a PR that fixes the problem with the tests failing. Please rebase this PR.

**Comment by devopsjesus** [comment]
Here were my thoughts on the _Read_ attribute for `Ensure`:

I tagged the `Ensure` property with the _Read_ attribute, since it seems that the xADDomainController resource doesn't really support the demotion of a DC using an **Absent** value for `Ensure`, and I didn't want to confuse users by having that option available to set in a configuration.  I figured if we want to add the ability to demote a DC, we could then change the property attribute with that feature request.

**Comment by johlju** [comment]
I’m good with that if there are not a problem using the resource if the parameter, and that we also create an issue to track that it should be made a Write property once we have the absent logic added. So it’s no confusing why it’s a read property in the future. 

Although, we could also make it a Write property today and create an issue tracking that Absent logic should be added. :thinking:

**Comment by devopsjesus** [comment]
Added Issue #251 to track the Ensure property is updated with a _Write_ attribute when implementing the feature to demote a DC using `Ensure = 'Absent'`

**Comment by johlju** [comment]
@devopsjesus This PR seems to want to added changes already changed in the dev-branch, for example the file `MSFT_xADObjectPermissionEntry.psm1`. Can you rebase  (`git rebase`) this PR again (so your commits are replayed over the dev-branch)?.

**Comment by devopsjesus** [comment]
did the rebase - I also merged upstream/dev into my fork, which might be why those extra file changes are shown?

**Comment by johlju** [comment]
@devopsjesus merged! Awesome work on this one! Thank you! 😄

**Pull request merged**
