### PR TITLE
New DSC Resource xKDSkey

### PR DESCRIPTION
**Pull request by rdbartram**
When creating gMSAs a KDSRootKey is required. This is simply a resource to create one.

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xactivedirectory/165)

### CODE REVIEW

**Comment by johlju** [comment]
Great work on this one too! :smiley:  A bunch of review comments. I will review the tests once these are resolved. 

---

Reviewed 3 of 5 files at r1, 1 of 1 files at r2.
Review status: 4 of 5 files reviewed at latest revision, all discussions resolved.

---

*[README.md, line 282 at r2](https://reviewable.io/reviews/powershell/xactivedirectory/165#-LC4BhJ92C3fV1zcOZbG:-LC4BhJ92C3fV1zcOZbH:beredxj) ([raw file](https://github.com/powershell/xactivedirectory/blob/b5b173f12a150644a87fb228bf647a36e6469d65/README.md#L282)):*
> ```Markdown
> Setting an ODJ Request file path for a configuration that creates a computer account that already exists will not cause the file to be created.
> 
> ### **xKDSKey**
> ```

Can we add the read-only parameters to this list as well? Like it is done here for example, see at the end of the Parameters section; https://github.com/PowerShell/SqlServerDsc#parameters

---

*[README.md, line 284 at r2](https://reviewable.io/reviews/powershell/xactivedirectory/165#-LC4Bv9tAN9Jh_AQVlle:-LC4Bv9tAN9Jh_AQVllf:b-vnpvzh) ([raw file](https://github.com/powershell/xactivedirectory/blob/b5b173f12a150644a87fb228bf647a36e6469d65/README.md#L284)):*
> ```Markdown
> ### **xKDSKey**
> The xKDSKey DSC resource will create KDS Keys within Active Directory.
> * **EffectiveTime**: Specifies the time at which key will become active.
> ```

Could we please do how these are documented in other resource? 🙂 Adding the type, and type qualifier. Like this.

```
* **`[String]` Parameter1** _(Key)_: Description.
* **`[Boolean]` Parameter2** _(Required)_: Description.
* **`[String]` Ensure** _(Write)_: Description. Default value is 'Present. { *Present* | Absent }
* **`[String[]]` Parameter3** _(Write)_: Description.
```

---

*[DSCResources/MSFT_xKDSKey/MSFT_xKDSKey.psm1, line 1 at r2](https://reviewable.io/reviews/powershell/xactivedirectory/165#-LC4C4Ib-rKKz5t5S5D9:-LC4C4Ib-rKKz5t5S5DA:b-6jtzyg) ([raw file](https://github.com/powershell/xactivedirectory/blob/b5b173f12a150644a87fb228bf647a36e6469d65/DSCResources/MSFT_xKDSKey/MSFT_xKDSKey.psm1#L1)):*
> ```PowerShell
> function Get-TargetResource {
> ```

Please add comments-based help to each function. Throughout.

---

*[DSCResources/MSFT_xKDSKey/MSFT_xKDSKey.psm1, line 1 at r2](https://reviewable.io/reviews/powershell/xactivedirectory/165#-LC4C8CU77mNdQaeEy9Y:-LC4C8CU77mNdQaeEy9Z:bsrtif7) ([raw file](https://github.com/powershell/xactivedirectory/blob/b5b173f12a150644a87fb228bf647a36e6469d65/DSCResources/MSFT_xKDSKey/MSFT_xKDSKey.psm1#L1)):*
> ```PowerShell
> function Get-TargetResource {
> ```

Please move the open brace to the next row (by itself). Throughout for functions and statements (like try-catch, if, etc.). Throughout.

---

*[DSCResources/MSFT_xKDSKey/MSFT_xKDSKey.psm1, line 6 at r2](https://reviewable.io/reviews/powershell/xactivedirectory/165#-LC4CQK02TK219fNHLVz:-LC4CQK02TK219fNHLW-:b-pgmbtp) ([raw file](https://github.com/powershell/xactivedirectory/blob/b5b173f12a150644a87fb228bf647a36e6469d65/DSCResources/MSFT_xKDSKey/MSFT_xKDSKey.psm1#L6)):*
> ```PowerShell
>     param
>     (
>         [Parameter(Mandatory)]
> ```

Please format these according to the style guideline (see your other PR for reference).

---

*[DSCResources/MSFT_xKDSKey/MSFT_xKDSKey.psm1, line 6 at r2](https://reviewable.io/reviews/powershell/xactivedirectory/165#-LC4Fm8p6fEj_wgEj6X6:-LC4Fm8p6fEj_wgEj6X7:bphjwzi) ([raw file](https://github.com/powershell/xactivedirectory/blob/b5b173f12a150644a87fb228bf647a36e6469d65/DSCResources/MSFT_xKDSKey/MSFT_xKDSKey.psm1#L6)):*
> ```
> Mandatory
> ```

`Mandatory = $true`

---

*[DSCResources/MSFT_xKDSKey/MSFT_xKDSKey.psm1, line 9 at r2](https://reviewable.io/reviews/powershell/xactivedirectory/165#-LC4FYGBE_R1gd_GlCtv:-LC4FYGBE_R1gd_GlCtw:bw5zm8z) ([raw file](https://github.com/powershell/xactivedirectory/blob/b5b173f12a150644a87fb228bf647a36e6469d65/DSCResources/MSFT_xKDSKey/MSFT_xKDSKey.psm1#L9)):*
> ```PowerShell
>         [DateTime] $EffectiveTime
>     )
> ```

Can we add a `Write-Verbose` and localized string here? 

---

*[DSCResources/MSFT_xKDSKey/MSFT_xKDSKey.psm1, line 11 at r2](https://reviewable.io/reviews/powershell/xactivedirectory/165#-LC4F9822uN7dvo1fHPj:-LC4F9822uN7dvo1fHPk:b-sk3edi) ([raw file](https://github.com/powershell/xactivedirectory/blob/b5b173f12a150644a87fb228bf647a36e6469d65/DSCResources/MSFT_xKDSKey/MSFT_xKDSKey.psm1#L11)):*
> ```
> $KDSKeys
> ```

$kdsKey (lower-case 'kds' and singular since only one item is returned). Throughout.

---

*[DSCResources/MSFT_xKDSKey/MSFT_xKDSKey.psm1, line 11 at r2](https://reviewable.io/reviews/powershell/xactivedirectory/165#-LC4NLlN1HNme7eOixlm:-LC4NLlN1HNme7eOixln:b-l2woyz) ([raw file](https://github.com/powershell/xactivedirectory/blob/b5b173f12a150644a87fb228bf647a36e6469d65/DSCResources/MSFT_xKDSKey/MSFT_xKDSKey.psm1#L11)):*
> ```PowerShell
> 
>     try {
>         $KDSKeys = Get-KDSRootKey | Select-Object -First 1
> ```

If there are more than one root key, you select the first. But is that the latest? Maybe sort them.

```
PS > Get-KDSRootKey

AttributeOfWrongFormat :
KeyValue               : {56, 87, 176, 98...}
EffectiveTime          : 2018-05-09 16:51:33
CreationTime           : 2018-05-09 16:51:33
IsFormatValid          : True
DomainController       : CN=DC1,OU=Domain Controllers,DC=company,DC=se
ServerConfiguration    : Microsoft.KeyDistributionService.Cmdlets.KdsServerConfiguration
KeyId                  : 61b6e784-336d-a301-4f47-2eaf6d4f3604
VersionNumber          : 1
```

---

*[DSCResources/MSFT_xKDSKey/MSFT_xKDSKey.psm1, line 35 at r2](https://reviewable.io/reviews/powershell/xactivedirectory/165#-LC4FpOnEIddSAwWdHqR:-LC4FpOnEIddSAwWdHqS:bphjwzi) ([raw file](https://github.com/powershell/xactivedirectory/blob/b5b173f12a150644a87fb228bf647a36e6469d65/DSCResources/MSFT_xKDSKey/MSFT_xKDSKey.psm1#L35)):*
> ```
> Mandatory
> ```

`Mandatory = $true`

---

*[DSCResources/MSFT_xKDSKey/MSFT_xKDSKey.psm1, line 38 at r2](https://reviewable.io/reviews/powershell/xactivedirectory/165#-LC4FgkxCkz6TWUugUtx:-LC4FgkxCkz6TWUugUty:bw5zm8z) ([raw file](https://github.com/powershell/xactivedirectory/blob/b5b173f12a150644a87fb228bf647a36e6469d65/DSCResources/MSFT_xKDSKey/MSFT_xKDSKey.psm1#L38)):*
> ```PowerShell
>         [DateTime] $EffectiveTime
>     )
> ```

Can we add a `Write-Verbose` and localized string here? 

---

*[DSCResources/MSFT_xKDSKey/MSFT_xKDSKey.psm1, line 39 at r2](https://reviewable.io/reviews/powershell/xactivedirectory/165#-LC4FsYI7Omcf7-BFME3:-LC4FsYI7Omcf7-BFME4:b-zeeomq) ([raw file](https://github.com/powershell/xactivedirectory/blob/b5b173f12a150644a87fb228bf647a36e6469d65/DSCResources/MSFT_xKDSKey/MSFT_xKDSKey.psm1#L39)):*
> ```
> $Keys
> ```

`$keys`, but rather `$getTargetResourceResult`.

---

*[DSCResources/MSFT_xKDSKey/MSFT_xKDSKey.psm1, line 42 at r2](https://reviewable.io/reviews/powershell/xactivedirectory/165#-LC4G7jR5fQx_UZrBk7j:-LC4G7jR5fQx_UZrBk7k:bw6vkkx) ([raw file](https://github.com/powershell/xactivedirectory/blob/b5b173f12a150644a87fb228bf647a36e6469d65/DSCResources/MSFT_xKDSKey/MSFT_xKDSKey.psm1#L42)):*
> ```
> get-date
> ```

`Get-Date` upper 'G' and 'D'

---

*[DSCResources/MSFT_xKDSKey/MSFT_xKDSKey.psm1, line 42 at r2](https://reviewable.io/reviews/powershell/xactivedirectory/165#-LC4GPJqDuGjOI9Bjp6v:-LC4GPJqDuGjOI9Bjp6w:bbgvm2x) ([raw file](https://github.com/powershell/xactivedirectory/blob/b5b173f12a150644a87fb228bf647a36e6469d65/DSCResources/MSFT_xKDSKey/MSFT_xKDSKey.psm1#L42)):*
> ```
> Where-Object {
> ```

We should use named arguments; `Where-Object -FilterScript {`

---

*[DSCResources/MSFT_xKDSKey/MSFT_xKDSKey.psm1, line 42 at r2](https://reviewable.io/reviews/powershell/xactivedirectory/165#-LC4HAgGCDGHdITBse3m:-LC4HAgGCDGHdITBse3n:b-98tpi7) ([raw file](https://github.com/powershell/xactivedirectory/blob/b5b173f12a150644a87fb228bf647a36e6469d65/DSCResources/MSFT_xKDSKey/MSFT_xKDSKey.psm1#L42)):*
> ```PowerShell
> 
>     if ($EffectiveTime -le (get-date)) {
>         [bool]($Keys.EffectiveTime | Where-Object {$_ -le (get-date)})
> ```

It feels like this evaluation is wrong. We should return $false it current date is higher than `$Keys.EffectiveTime`? It seems it returns `$true` all the time, when I run this:

```
$effectiveTime = [Datetime]'2018-05-08'
$currentDate = [Datetime]'2018-05-07'
[bool]$effectiveTime | Where-Object { $_ -le $currentDate }
$currentDate = [Datetime]'2018-05-10'
[bool]$effectiveTime | Where-Object { $_ -le $currentDate }
```

---

*[DSCResources/MSFT_xKDSKey/MSFT_xKDSKey.psm1, line 45 at r2](https://reviewable.io/reviews/powershell/xactivedirectory/165#-LC4GXfVByeog1N1PAuk:-LC4GXfVByeog1N1PAul:bbgvm2x) ([raw file](https://github.com/powershell/xactivedirectory/blob/b5b173f12a150644a87fb228bf647a36e6469d65/DSCResources/MSFT_xKDSKey/MSFT_xKDSKey.psm1#L45)):*
> ```
> Where-Object {
> ```

We should use named arguments; `Where-Object -FilterScript {`

---

*[DSCResources/MSFT_xKDSKey/MSFT_xKDSKey.psm1, line 45 at r2](https://reviewable.io/reviews/powershell/xactivedirectory/165#-LC4IcIH65RMReC7g3yl:-LC4IcIH65RMReC7g3ym:b-l968u7) ([raw file](https://github.com/powershell/xactivedirectory/blob/b5b173f12a150644a87fb228bf647a36e6469d65/DSCResources/MSFT_xKDSKey/MSFT_xKDSKey.psm1#L45)):*
> ```PowerShell
>     }
>     else {
>         [bool]($Keys.EffectiveTime | Where-Object {$_ -eq $EffectiveTime})
> ```

Same question about the evaluation here.

---

*[DSCResources/MSFT_xKDSKey/MSFT_xKDSKey.psm1, line 54 at r2](https://reviewable.io/reviews/powershell/xactivedirectory/165#-LC4Fq2s1WDz14wTOmsz:-LC4Fq2s1WDz14wTOmt-:bphjwzi) ([raw file](https://github.com/powershell/xactivedirectory/blob/b5b173f12a150644a87fb228bf647a36e6469d65/DSCResources/MSFT_xKDSKey/MSFT_xKDSKey.psm1#L54)):*
> ```
> Mandatory
> ```

`Mandatory = $true`

---

*[DSCResources/MSFT_xKDSKey/MSFT_xKDSKey.psm1, line 57 at r2](https://reviewable.io/reviews/powershell/xactivedirectory/165#-LC4FhZs3XsN3Mynwp3f:-LC4FhZs3XsN3Mynwp3g:bw5zm8z) ([raw file](https://github.com/powershell/xactivedirectory/blob/b5b173f12a150644a87fb228bf647a36e6469d65/DSCResources/MSFT_xKDSKey/MSFT_xKDSKey.psm1#L57)):*
> ```PowerShell
>         [DateTime] $EffectiveTime
>     )
> ```

Can we add a `Write-Verbose` and localized string here? 

---

*[DSCResources/MSFT_xKDSKey/MSFT_xKDSKey.psm1, line 58 at r2](https://reviewable.io/reviews/powershell/xactivedirectory/165#-LC4JIau4hGdyF_ZhEEC:-LC4JIau4hGdyF_ZhEED:bfi2krm) ([raw file](https://github.com/powershell/xactivedirectory/blob/b5b173f12a150644a87fb228bf647a36e6469d65/DSCResources/MSFT_xKDSKey/MSFT_xKDSKey.psm1#L58)):*
> ```
> $Params
> ```

Can we change to `$parameters` (try to avoid abbreviations). But personally I would rather see `$addKdsRootKeyParameters`. 

---

*[DSCResources/MSFT_xKDSKey/MSFT_xKDSKey.psm1, line 60 at r2](https://reviewable.io/reviews/powershell/xactivedirectory/165#-LC4K-l45CHiOrk-EbqJ:-LC4K-l45CHiOrk-EbqK:b-e5eigj) ([raw file](https://github.com/powershell/xactivedirectory/blob/b5b173f12a150644a87fb228bf647a36e6469d65/DSCResources/MSFT_xKDSKey/MSFT_xKDSKey.psm1#L60)):*
> ```PowerShell
>     $Params = @{}
> 
>     if ($EffectiveTime -le (get-date)) {
> ```

if a configuration has the `EffectiveTime` value set to a date less than Get-Date, then that value will always be less than Get-date, will this will update every 15 minutes (default wait time for LCM)? Is that the intended behavior? 

---

*[DSCResources/MSFT_xKDSKey/MSFT_xKDSKey.psm1, line 67 at r2](https://reviewable.io/reviews/powershell/xactivedirectory/165#-LC4LoEW6cOOjuSQ4uMt:-LC4LoEW6cOOjuSQ4uMu:bfngdns) ([raw file](https://github.com/powershell/xactivedirectory/blob/b5b173f12a150644a87fb228bf647a36e6469d65/DSCResources/MSFT_xKDSKey/MSFT_xKDSKey.psm1#L67)):*
> ```PowerShell
>     }
> 
>     Add-KDSRootKey @params | out-null
> ```

Should this use `-Confirm:$false`? 

---

*[DSCResources/MSFT_xKDSKey/MSFT_xKDSKey.meta.mof, line 1 at r2](https://reviewable.io/reviews/powershell/xactivedirectory/165#-LC4F-E9ChjfIFrerc0s:-LC4F-E9ChjfIFrerc0t:b19dalg) ([raw file](https://github.com/powershell/xactivedirectory/blob/b5b173f12a150644a87fb228bf647a36e6469d65/DSCResources/MSFT_xKDSKey/MSFT_xKDSKey.meta.mof#L1)):*
> ```
> 1.0.1.0
> ```

I suggest we change this to '1.0.0.0'.

---

*[DSCResources/MSFT_xKDSKey/MSFT_xKDSKey.meta.mof, line 4 at r2](https://reviewable.io/reviews/powershell/xactivedirectory/165#-LC4IrT63rM1hm_tcuNz:-LC4IrT63rM1hm_tcuO-:b-27vtlg) ([raw file](https://github.com/powershell/xactivedirectory/blob/b5b173f12a150644a87fb228bf647a36e6469d65/DSCResources/MSFT_xKDSKey/MSFT_xKDSKey.meta.mof#L4)):*
> ```
> class MSFT_xKDSKey : OMI_BaseResource
> {
>     [Key, Description("Time at which key will become active")] DateTime EffectiveTime;
> ```

Should we make this as "single instance resource" by adding the property `IsSingleInstance` as key instead of `EffectiveTime`? See https://docs.microsoft.com/en-us/powershell/dsc/singleinstance

That will prevent adding this resource several times in a configuration with different values.

---


*Comments from [Reviewable](https://reviewable.io/reviews/powershell/xactivedirectory/165#-:-LC4PcSqDj8ofO5dBRVL:br0bam7)*

**Comment by johlju** [comment]
Labeling as abandoned since it has gone 14 days until last update. An abandoned PR can be continued by another contributor. The abandoned label will be removed if work on the PR is taken up again.

**Comment by gaelcolas** [comment]
Hi @rdbartram :)
Any chance to look on that one? Let me know if you need a hand.

**Comment by kungfu71186** [comment]
@rdbartram @gaelcolas Currently helping with the gMSA/MSA resource. This resource will be useful for that. I can also help on this one as well.

**Comment by johlju** [comment]
@kungfu71186 I think it safe for you to take over this one since it has been no active for a while on this one. Look here how to take over this PR https://github.com/PowerShell/DscResources/blob/master/GettingStartedWithGitHub.md#how-to-continue-working-on-a-pull-request-pr-when-an-author-contributor-is-unable-to-complete-it

Just add `Closes #165` on the new PR you send in.

**Comment by johlju** [comment]
@kungfu71186 Would you like to work on this PR next? :grin:

**Comment by kungfu71186** [comment]
@johlju yes, i can

**Pull request closed without merging**
