### PR TITLE
Adds xADComputer Resource

### LINKED ISSUE #67: Bug in xADDomainController
On the Get-TargetResource section, the write-verbose statement calls for a $fullDomainName variable that isn't defined.

### LINKED ISSUE #69: Add xADComputer
I'm using DSC to create clusters and it would be nice/easier if there was a xADComputer to add computer objects to the domain ahead of creating the cluster.  Suggested parameters would be OU location and account Enabled = True/False.  Looking for the Enabled parameter as cluster computer objects need to be disabled before creating the cluster.

### PR DESCRIPTION
**Pull request by iainbrighton**
* Ignores DSCResource.Tests
* Updates readme and adds example
* Adds unit test coverage
* Fixes #69
* Fixes #67

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xactivedirectory/96)

### CODE REVIEW

**Comment by iainbrighton** [comment]
One for you @PlagueHO!

**Comment by PlagueHO** [comment]
@iainbrighton  - You're a legend! I'll review tonight (unless someone else gets there first)! :+1:

**Comment by PlagueHO** [comment]
Reviewed 1 of 2 files at r1, 11 of 11 files at r2.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[README.md, line 233 \[r2\]](https://reviewable.io:443/reviews/powershell/xactivedirectory/96#-KIC0FiR-PNXrKZrz8bR:-KIC0FiSuSg39gWv9ido:-222699833) ([raw file](https://github.com/powershell/xactivedirectory/blob/f90dd1f73f622323867efeececac081c9ea6919a/README.md#L233)):*
> ```Markdown
> 
> ### Unreleased
> ```

You should add a mention of fixing the verbose log messages and the changes (minor) to xADGroup and xADUser.

---

*[DSCResources/MSFT_xADCommon/MSFT_xADCommon.ps1, line 303 \[r2\]](https://reviewable.io:443/reviews/powershell/xactivedirectory/96#-KIC0lwT5YJUFnvpKTES:-KIC0lwT5YJUFnvpKTET:-343827491) ([raw file](https://github.com/powershell/xactivedirectory/blob/f90dd1f73f622323867efeececac081c9ea6919a/DSCResources/MSFT_xADCommon/MSFT_xADCommon.ps1#L303)):*
> ```PowerShell
>             if ($member -notin $ExistingMembers)
>             {
>                 Write-Verbose -Message ($localizedString.MemberNotInDesiredState -f $member);;
> ```

Nitpick: Even though you didn't add it, can we remove the 2nd semicolon at the end of the line?

---

*[Tests/Unit/MSFT_xADComputer.Tests.ps1, line 4 \[r2\]](https://reviewable.io:443/reviews/powershell/xactivedirectory/96#-KIC5R00JoXGTqv1w5rT:-KIC5R01sXboG3weOIjx:1269796588) ([raw file](https://github.com/powershell/xactivedirectory/blob/f90dd1f73f622323867efeececac081c9ea6919a/Tests/Unit/MSFT_xADComputer.Tests.ps1#L4)):*
> ```PowerShell
> $Global:DSCResourceName    = 'MSFT_xADComputer' # Example MSFT_xFirewall
> 
> #region HEADER
> ```

Can you convert the template into the new version (v1.1.0) [Unit Test Template](https://github.com/PowerShell/DscResources/blob/master/Tests.Template/unit_template.ps1)?

---

*[Tests/Unit/MSFT_xADComputer.Tests.ps1, line 28 \[r2\]](https://reviewable.io:443/reviews/powershell/xactivedirectory/96#-KIC5x9Q32VXGqLg9ooZ:-KIC5x9Q32VXGqLg9oo_:-258448875) ([raw file](https://github.com/powershell/xactivedirectory/blob/f90dd1f73f622323867efeececac081c9ea6919a/Tests/Unit/MSFT_xADComputer.Tests.ps1#L28)):*
> ```PowerShell
>     # The InModuleScope command allows you to perform white-box unit testing on the internal
>     # (non-exported) code of a Script Module.
>     InModuleScope $Global:DSCResourceName {
> ```

You should probably get rid of the InModuleScope block as it isn't required. The templates got changed a few weeks ago to remove this so that it was only included when private functions needed to be tested.

---

*[Tests/Unit/MSFT_xADComputer.Tests.ps1, line 56 \[r2\]](https://reviewable.io:443/reviews/powershell/xactivedirectory/96#-KIC6PDT0FidRlqK3J1f:-KIC6PDUXc7X1_ONhSia:1794323756) ([raw file](https://github.com/powershell/xactivedirectory/blob/f90dd1f73f622323867efeececac081c9ea6919a/Tests/Unit/MSFT_xADComputer.Tests.ps1#L56)):*
> ```PowerShell
> 
>         $testDomainController = 'TESTDC';
>         $testCredential = New-Object System.Management.Automation.PSCredential 'DummyUser', (ConvertTo-SecureString 'DummyPassword' -AsPlainText -Force);
> ```

PSSA is probably going to throw a hissy fit about this line so we'd need to add a [Diagnostics.CodeAnalysis.SuppressMessageAttribute("PSAvoidUsingConvertToSecureStringWithPlainText", "")]

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xactivedirectory/96)*

**Comment by iainbrighton** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[README.md, line 233 \[r2\]](https://reviewable.io:443/reviews/powershell/xactivedirectory/96#-KIC0FiR-PNXrKZrz8bR:-KIF8MwTC9dda0FDZ5IU:676635175) ([raw file](https://github.com/powershell/xactivedirectory/blob/f90dd1f73f622323867efeececac081c9ea6919a/README.md#L233)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary>
> You should add a mention of fixing the verbose log messages and the changes (minor) to xADGroup and xADUser.
</details>
Done

---

*[DSCResources/MSFT_xADCommon/MSFT_xADCommon.ps1, line 303 \[r2\]](https://reviewable.io:443/reviews/powershell/xactivedirectory/96#-KIC0lwT5YJUFnvpKTES:-KIF8ODXPKVtsDXxbIMo:15771039) ([raw file](https://github.com/powershell/xactivedirectory/blob/f90dd1f73f622323867efeececac081c9ea6919a/DSCResources/MSFT_xADCommon/MSFT_xADCommon.ps1#L303)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary>
> Nitpick: Even though you didn't add it, can we remove the 2nd semicolon at the end of the line?
</details>
Done (it probably was me at some point!)

---

*[Tests/Unit/MSFT_xADComputer.Tests.ps1, line 4 \[r2\]](https://reviewable.io:443/reviews/powershell/xactivedirectory/96#-KIC5R00JoXGTqv1w5rT:-KIF7l12kgGCuCraym9y:1369616203) ([raw file](https://github.com/powershell/xactivedirectory/blob/f90dd1f73f622323867efeececac081c9ea6919a/Tests/Unit/MSFT_xADComputer.Tests.ps1#L4)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary>
> Can you convert the template into the new version (v1.1.0) [Unit Test Template](https://github.com/PowerShell/DscResources/blob/master/Tests.Template/unit_template.ps1)?
</details>
I attempted to update the template and _everything_ blew up. Now, this might be due to not being able to install the AD RSAT tools on the latest Win 10 slow ring build. I will try in a VM over the weekend/early next week.

---

*[Tests/Unit/MSFT_xADComputer.Tests.ps1, line 28 \[r2\]](https://reviewable.io:443/reviews/powershell/xactivedirectory/96#-KIC5x9Q32VXGqLg9ooZ:-KIF8WthYxNscUCcRrUh:-310385951) ([raw file](https://github.com/powershell/xactivedirectory/blob/f90dd1f73f622323867efeececac081c9ea6919a/Tests/Unit/MSFT_xADComputer.Tests.ps1#L28)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary>
> You should probably get rid of the InModuleScope block as it isn't required. The templates got changed a few weeks ago to remove this so that it was only included when private functions needed to be tested.
</details>
Acknowledged.

---

*[Tests/Unit/MSFT_xADComputer.Tests.ps1, line 56 \[r2\]](https://reviewable.io:443/reviews/powershell/xactivedirectory/96#-KIC6PDT0FidRlqK3J1f:-KIF8AY8Z_uYuYpcWhj7:-74192486) ([raw file](https://github.com/powershell/xactivedirectory/blob/f90dd1f73f622323867efeececac081c9ea6919a/Tests/Unit/MSFT_xADComputer.Tests.ps1#L56)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary>
> PSSA is probably going to throw a hissy fit about this line so we'd need to add a [Diagnostics.CodeAnalysis.SuppressMessageAttribute("PSAvoidUsingConvertToSecureStringWithPlainText", "")]
</details>
Can the attribute be placed at the beginning of a .PS1 file (outside of a function)? Not checked, but will try and see what the PSSA says..

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xactivedirectory/96)*

**Comment by iainbrighton** [comment]
Review status: 10 of 12 files reviewed at latest revision, 5 unresolved discussions.

---

*[Tests/Unit/MSFT_xADComputer.Tests.ps1, line 4 \[r2\]](https://reviewable.io:443/reviews/powershell/xactivedirectory/96#-KIC5R00JoXGTqv1w5rT:-KITG0DxdTC0PhQWA6-k:-427155719) ([raw file](https://github.com/powershell/xactivedirectory/blob/f90dd1f73f622323867efeececac081c9ea6919a/Tests/Unit/MSFT_xADComputer.Tests.ps1#L4)):*
<details><summary><i>Previously, iainbrighton (Iain Brighton) wrote…</i></summary>
> I attempted to update the template and _everything_ blew up. Now, this might be due to not being able to install the AD RSAT tools on the latest Win 10 slow ring build. I will try in a VM over the weekend/early next week.
</details>
@PlagueHO Removing the `InModuleScope` scriptblock causes me a real problem and results in __every__ test failing. All I receive are `The term 'xxx-TargetResource' is not recognized as the name of a cmdlet`. Here's an example:
```
Describing MSFT_xADComputer\Get-TargetResource
 [-] Returns a 'System.Collections.Hashtable' object type 9.01s
   The term 'Get-TargetResource' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
   at line: 65 in C:\Users\iainb\Dropbox\PowerShell\DSC\Resources\xActiveDirectory\Tests\Unit\MSFT_xADComputer.Tests.ps1
 [-] Returns 'Ensure' is 'Present' when user account exists 161ms
   The term 'Get-TargetResource' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
   at line: 73 in C:\Users\iainb\Dropbox\PowerShell\DSC\Resources\xActiveDirectory\Tests\Unit\MSFT_xADComputer.Tests.ps1
 [-] Returns 'Ensure' is 'Absent' when user account does not exist 165ms
   The term 'Get-TargetResource' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
   at line: 81 in C:\Users\iainb\Dropbox\PowerShell\DSC\Resources\xActiveDirectory\Tests\Unit\MSFT_xADComputer.Tests.ps1
 [-] Calls 'Get-ADComputer' with 'Server' parameter when 'DomainController' specified 163ms
   The term 'Get-TargetResource' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
   at line: 89 in C:\Users\iainb\Dropbox\PowerShell\DSC\Resources\xActiveDirectory\Tests\Unit\MSFT_xADComputer.Tests.ps1
 [-] Calls 'Get-ADComputer' with 'Credential' parameter when 'DomainAdministratorCredential' specified 164ms
   The term 'Get-TargetResource' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
   at line: 97 in C:\Users\iainb\Dropbox\PowerShell\DSC\Resources\xActiveDirectory\Tests\Unit\MSFT_xADComputer.Tests.ps1
```
I've not had a real chance to dig into what the test helper(s) are doing, but it looks like the module's not imported correctly. It might be something to do with my setup though. Ideas?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xactivedirectory/96)*

**Comment by PlagueHO** [comment]
Superb work on this BTW! :+1:

<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary>
> @iainbrighton  - You're a legend! I'll review tonight (unless someone else gets there first)! :+1: 
</details>


---

Reviewed 4 of 4 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[Tests/Unit/MSFT_xADComputer.Tests.ps1, line 4 \[r2\]](https://reviewable.io:443/reviews/powershell/xactivedirectory/96#-KIC5R00JoXGTqv1w5rT:-KIWQvcPr38DjUqVI4Fc:-1497089724) ([raw file](https://github.com/powershell/xactivedirectory/blob/f90dd1f73f622323867efeececac081c9ea6919a/Tests/Unit/MSFT_xADComputer.Tests.ps1#L4)):*
<details><summary><i>Previously, iainbrighton (Iain Brighton) wrote…</i></summary>
> @PlagueHO Removing the `InModuleScope` scriptblock causes me a real problem and results in __every__ test failing. All I receive are `The term 'xxx-TargetResource' is not recognized as the name of a cmdlet`. Here's an example:
> ```
> Describing MSFT_xADComputer\Get-TargetResource
>  [-] Returns a 'System.Collections.Hashtable' object type 9.01s
>    The term 'Get-TargetResource' is not recognized as the name of a cmdlet, function, script file, or operable program.
> Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
>    at line: 65 in C:\Users\iainb\Dropbox\PowerShell\DSC\Resources\xActiveDirectory\Tests\Unit\MSFT_xADComputer.Tests.ps1
>  [-] Returns 'Ensure' is 'Present' when user account exists 161ms
>    The term 'Get-TargetResource' is not recognized as the name of a cmdlet, function, script file, or operable program.
> Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
>    at line: 73 in C:\Users\iainb\Dropbox\PowerShell\DSC\Resources\xActiveDirectory\Tests\Unit\MSFT_xADComputer.Tests.ps1
>  [-] Returns 'Ensure' is 'Absent' when user account does not exist 165ms
>    The term 'Get-TargetResource' is not recognized as the name of a cmdlet, function, script file, or operable program.
> Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
>    at line: 81 in C:\Users\iainb\Dropbox\PowerShell\DSC\Resources\xActiveDirectory\Tests\Unit\MSFT_xADComputer.Tests.ps1
>  [-] Calls 'Get-ADComputer' with 'Server' parameter when 'DomainController' specified 163ms
>    The term 'Get-TargetResource' is not recognized as the name of a cmdlet, function, script file, or operable program.
> Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
>    at line: 89 in C:\Users\iainb\Dropbox\PowerShell\DSC\Resources\xActiveDirectory\Tests\Unit\MSFT_xADComputer.Tests.ps1
>  [-] Calls 'Get-ADComputer' with 'Credential' parameter when 'DomainAdministratorCredential' specified 164ms
>    The term 'Get-TargetResource' is not recognized as the name of a cmdlet, function, script file, or operable program.
> Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
>    at line: 97 in C:\Users\iainb\Dropbox\PowerShell\DSC\Resources\xActiveDirectory\Tests\Unit\MSFT_xADComputer.Tests.ps1
> ```
> I've not had a real chance to dig into what the test helper(s) are doing, but it looks like the module's not imported correctly. It might be something to do with my setup though. Ideas?
</details>
I'm scratching my head on this. It "should" work just fine. Let me have a dig about in some of my modules and see if I can replicate the problem. I might clone your repo and see if it happens with mine. Not good - don't want to be telling people to remove the InModuleScope if it in fact requires it!

---

*[Tests/Unit/MSFT_xADComputer.Tests.ps1, line 56 \[r2\]](https://reviewable.io:443/reviews/powershell/xactivedirectory/96#-KIC6PDT0FidRlqK3J1f:-KIWQ2pSO2vcgISeFX21:-1555327648) ([raw file](https://github.com/powershell/xactivedirectory/blob/f90dd1f73f622323867efeececac081c9ea6919a/Tests/Unit/MSFT_xADComputer.Tests.ps1#L56)):*
<details><summary><i>Previously, iainbrighton (Iain Brighton) wrote…</i></summary>
> Can the attribute be placed at the beginning of a .PS1 file (outside of a function)? Not checked, but will try and see what the PSSA says..
</details>
I think it can be - at least the documentation says it can be: https://github.com/PowerShell/PSScriptAnalyzer#suppressing-rules

Although I think outside a function you need to add:
```[Diagnostics.CodeAnalysis.SuppressMessageAttribute("PSAvoidUsingConvertToSecureStringWithPlainText", "", Scope="Function")]```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xactivedirectory/96#-:-KIWQpBghtym1eLU-sdf:815621954)*

**Comment by iainbrighton** [comment]
Thinking about this (on the train), isn't the module imported inside the TestHelper scope? This is a different scope to where the Pester tests are executed and might be why they can't be found..?

**Comment by PlagueHO** [comment]
@iainbrighton - oh my - you could very well be correct. That would make a lot of sense. I say we use InModuleScope until we figure out a solution.

If there is no solution then we need to revert the Test.Templates and the TestGuidelines.

@KarolKaczmarek, @narrieta - can you think of a way around this problem: If the DSC Resource being tested is being imported by the Test.Helper.psm1 module, not by the actual unit test script, then it is not in the scope of the unit test script - so the tests needs to be in an InModuleScope block.

**Comment by narrieta** [comment]
@PlagueHO - in my opinion the module to test should be imported within the scope of the test script, rather than in the scope of Test.Helper.psm1. Importing at the global scope (Import-Module -Global) may also work, though I think the first option would be preferable.

One question regarding the import: Initialize-TestEnvironment explicitly removes the module before importing it. Is Import-Module -Force not enough?

One observation about Initialize-TestEnvironment: when I tried to execute the unit tests for ADComputer my PowerShell session seemed to hang so I had to kill the process. From then on, all the new PowerShell instances I started were extremely slow. The issue turned out to be duplicated entries in PSModulePath. Initialize-TestEnvironment changes the module path at the machine level; consider changing it at the process level and checking for duplicates. The execution policy should probably also be changed at the process level.

**Comment by PlagueHO** [comment]
@narrieta - thank you for looking at this and the info.

Regarding the Import-Module -Force - I think you're right, using the -Force parameter should be enough.

As for the Initialize-TestEnvironment problems, there is actually an [issue in place](https://github.com/PowerShell/DscResource.Tests/issues/55) that relates to this. I'm looking at doing some work on this but was just waiting to get a bit more feed back before proceeding. But it looks like the issues are really mounting up with this stuff so I might just go ahead and PR a solution and let people comment on that. I do agree though, the PSModulePath should only be changed at the process level - but only for the unit tests. For the integration tests to work this still requires the machine level changes because the LCM runs under a different process.

Thanks again for commenting on this - sorry @iainbrighton for hijacking this PR.

**Comment by iainbrighton** [comment]
@PlagueHO @narrieta No problem! If the import in the TestHelper.psm1 is changed to `Import-Module -Name $DSCModuleFile.FullName -Force -Scope Global`, then I can see the publicly exported *-TargetResource functions.

However, I can't seem to then mock the internal calls to Get-TargetResource from the Test- and Set-TargetResource functions without the InModuleScope [sigh].

**Comment by narrieta** [comment]
@iainbrighton @PlagueHO OK, too bad -Global doesn't work. I would recommend then importing the module to test from the test script instead of from TestHelper.psm1. It may be a small inconvenience but then only the code that actually needs access to the privates of the module needs to use InModuleScope (instead of the entire code of the test). Especially if we are doing this in the template that new test should follow.

**Comment by PlagueHO** [comment]
@narrieta, @iainbrighton  - I've moved this issue out into a new issue in DSCResource.tests. Thanks heaps for looking into all of this.

**Comment by TravisEz13** [comment]
Reviewed 1 of 2 files at r1, 7 of 11 files at r2, 3 of 4 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[Tests/Unit/MSFT_xADComputer.Tests.ps1, line 4 \[r2\]](https://reviewable.io:443/reviews/powershell/xactivedirectory/96#-KIC5R00JoXGTqv1w5rT:-KIjMK1BwBHb1apa1qSQ:683996060) ([raw file](https://github.com/powershell/xactivedirectory/blob/f90dd1f73f622323867efeececac081c9ea6919a/Tests/Unit/MSFT_xADComputer.Tests.ps1#L4)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary>
> I'm scratching my head on this. It "should" work just fine. Let me have a dig about in some of my modules and see if I can replicate the problem. I might clone your repo and see if it happens with mine. Not good - don't want to be telling people to remove the InModuleScope if it in fact requires it!
</details>
Why did we remove InModuleScope?  Resources with private functions won't be able to be tested without this. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xactivedirectory/96)*

**Comment by TravisEz13** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[Tests/Unit/MSFT_xADComputer.Tests.ps1, line 4 \[r2\]](https://reviewable.io:443/reviews/powershell/xactivedirectory/96#-KIC5R00JoXGTqv1w5rT:-KIjY6aaYHtP7u6iiMMG:-1489471959) ([raw file](https://github.com/powershell/xactivedirectory/blob/f90dd1f73f622323867efeececac081c9ea6919a/Tests/Unit/MSFT_xADComputer.Tests.ps1#L4)):*
<details><summary><i>Previously, TravisEz13 (Travis Plunk) wrote…</i></summary>
> Why did we remove InModuleScope?  Resources with private functions won't be able to be tested without this. 
</details>
I got my answer offline.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xactivedirectory/96)*

**Comment by PlagueHO** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[Tests/Unit/MSFT_xADComputer.Tests.ps1, line 4 \[r2\]](https://reviewable.io:443/reviews/powershell/xactivedirectory/96#-KIC5R00JoXGTqv1w5rT:-KIlOCEc3OlTdnD7idq5:939435168) ([raw file](https://github.com/powershell/xactivedirectory/blob/f90dd1f73f622323867efeececac081c9ea6919a/Tests/Unit/MSFT_xADComputer.Tests.ps1#L4)):*
<details><summary><i>Previously, TravisEz13 (Travis Plunk) wrote…</i></summary>
> I got my answer offline.
</details>
Here are the original discussions for a bit more context:
https://github.com/PowerShell/DscResources/issues/115
https://github.com/PowerShell/DscResources/issues/123

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xactivedirectory/96)*

**Comment by TravisEz13** [comment]
I reviewed, two discussions waiting on @iainbrighton  and @plagueho  to  say they are satisfied​ with the resolution.

<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary>
> @narrieta, @iainbrighton  - I've moved this issue out into a new issue in DSCResource.tests. Thanks heaps for looking into all of this.
</details>


---

Reviewed 1 of 4 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xactivedirectory/96#-:-KIz8EHOLQlmu0RQwQam:300157028)*

**Comment by iainbrighton** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[Tests/Unit/MSFT_xADComputer.Tests.ps1, line 56 \[r2\]](https://reviewable.io:443/reviews/powershell/xactivedirectory/96#-KIC6PDT0FidRlqK3J1f:-KJ4qHNWPmD676_TUs4n:845438726) ([raw file](https://github.com/powershell/xactivedirectory/blob/f90dd1f73f622323867efeececac081c9ea6919a/Tests/Unit/MSFT_xADComputer.Tests.ps1#L56)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary>
> I think it can be - at least the documentation says it can be: https://github.com/PowerShell/PSScriptAnalyzer#suppressing-rules
> 
> Although I think outside a function you need to add:
> ```[Diagnostics.CodeAnalysis.SuppressMessageAttribute("PSAvoidUsingConvertToSecureStringWithPlainText", "", Scope="Function")]```
</details>
I think using an empty [PSCredential] is the "cleaner" way of solving this (rather than suppressing the rule)?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xactivedirectory/96)*

**Comment by PlagueHO** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[Tests/Unit/MSFT_xADComputer.Tests.ps1, line 56 \[r2\]](https://reviewable.io:443/reviews/powershell/xactivedirectory/96#-KIC6PDT0FidRlqK3J1f:-KJ4xL4bKCTMK0sGDlTC:-2000885129) ([raw file](https://github.com/powershell/xactivedirectory/blob/f90dd1f73f622323867efeececac081c9ea6919a/Tests/Unit/MSFT_xADComputer.Tests.ps1#L56)):*
<details><summary><i>Previously, iainbrighton (Iain Brighton) wrote…</i></summary>
> I think using an empty [PSCredential] is the "cleaner" way of solving this (rather than suppressing the rule)?
</details>
I'm all for the cleaner way!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xactivedirectory/96)*

**Pull request merged**
