### PR TITLE
Remove duplicate example in README.md and fix xADUser schema version

### LINKED ISSUE #190: xADUser: schema.mof has a version number different from all other resources.
All resource has version 1.0.0.0 in the schema.mof, but xUser has 1.0.1.0. Unless there is a good reason for keeping it, I suggest we change xUser to use the same version number as all other resources.

### LINKED ISSUE #198: Duplication of code in example in readme.md
In the first example, asserting a highly available domain, the entire block of code intended for the example has been pasted in twice.

### PR DESCRIPTION
**Pull request by thequietman44**
- Removed duplicate config in README.md.
- Changed xADUser version to "1.0.0.0" to match other resources.

Fixes #190 
Fixes #198 

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xactivedirectory/206)

### CODE REVIEW

**Comment by johlju** [comment]
@thequietman44 Thanks for fixing this! 😄  I updated the PR title and description. We need resolve a problem with this PR before I can review. This PR is proposing to change (among other things) the same thing as you did in the last PR, see here https://github.com/PowerShell/xActiveDirectory/pull/206/files#diff-04c6e90faac2675aa89e2176d2eec7d8 you will see it want to remove the previous example you removed in the previous PR. 

This is easily resolved by rebasing against the upstream (origin) dev branch, but since you are using the dev branch as the working branch it can be a bit trickier. Normally you follow this guide [Resolve merge conflicts](https://github.com/PowerShell/DscResources/blob/master/GettingStartedWithGitHub.md#resolve-merge-conflicts).
But now I think we need to do this (from my head, so might be wrong).

```
# Run this to get the remote names and where they pointing
git remote -v 
# Make sure we are on dev (your working branch)
git checkout dev
# Replace 'origin' below with the name of the remote that points to the '.../PowerShell/xActiveDirectory'
git fetch origin dev
git rebase origin/dev
# Resolve merge conflicts (if any), refer to link to guide above, how to resolve merge conflicts.
(instead of branching `git checkout -b my-working-branch`).
# Only when merge conflicts are resolved, run this to push to your fork. Change 'my' to the remote name that points to your fork '.../thequietman44/xActiveDirectory'
git push my dev --force
```

If this doesn't work, then easiest is just to close the PR, and then clone repo again, and create a working-branch to work on, then do the changes again and PR in a new change from the new working branch.

```
cd MyNewEmptyFolder
git clone https://github.com/PowerShell/xActiveDirectory
git remote add my https://github.com/thequietman44/xActiveDirectory
git checkout -b my-working-branch-name
# You are now in a clean working branch - do the changes and then push to your fork.
git push my my-working-branch-name
# Send in the PR as usual.
```

**Comment by johlju** [comment]
No worries, we all was new at some point, happy to explain. 🙂 

It seems you got it! PR looks good! 😃 You we got a new "merge" commit, but I resolve that when i merge.

Btw. When doing rebase you should not get a commit 'Merge remote-tracking branch 'upstream/dev' into dev'. These are usually because `git pull` or `git merge` was used, when instead `git rebase` should have been used. 🙂 

I will review this PR now! Thanks!

**Comment by johlju** [comment]
Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed, 1 unresolved discussion (waiting on @thequietman44)

---

*[a discussion](https://reviewable.io/reviews/powershell/xactivedirectory/206#-LEtw0le2vPh38q3T3U1:-LEtw0le2vPh38q3T3U2:bgx6ujw) (no related file):*
Could you please add an descriptive entry, for each change/issue, to the Unreleased section of the change log in the file README.md? If an entry resolves an issue please reference the issue where applicable. You may suffix (it's optional) each entry with your name. Example of the format for the entry.
```
* Descriptive entry ([issue #123](https://github.com/PowerShell/xPSDesiredStateConfiguration/issues/123). [Name/Alias (@github_account)](https://github.com/github_account)
```

---


*Comments from [Reviewable](https://reviewable.io/reviews/powershell/xactivedirectory/206)*

**Comment by johlju** [comment]
When you have resolved the review comments, or if you need to discuss a comment. Could you please go into Reviewable and write 'Done' (or click the done-button) on each of the review comments. This allows me to acknowledge (resolve) the review comments and I know that you are done with each change. After you written 'Done' on each review comment,  or comment on the review comment if it needs further discussion, then click the big green 'Publish' button on top of the page. That will send all your comments back as one big comment to this PR.
You find Reviewable if you click on the big purple Reviewable-button in the PR description.

**Comment by thequietman44** [comment]
Review status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @johlju)

---

*[a discussion](https://reviewable.io/reviews/powershell/xactivedirectory/206#-LEtw0le2vPh38q3T3U1:-LEu-YX2Dwo3o_lnb3fE:b-896fix) (no related file):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Could you please add an descriptive entry, for each change/issue, to the Unreleased section of the change log in the file README.md? If an entry resolves an issue please reference the issue where applicable. You may suffix (it's optional) each entry with your name. Example of the format for the entry.
```
* Descriptive entry ([issue #123](https://github.com/PowerShell/xPSDesiredStateConfiguration/issues/123). [Name/Alias (@github_account)](https://github.com/github_account)
```

</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/powershell/xactivedirectory/206)*

**Comment by johlju** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: :shipit: complete! all files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/powershell/xactivedirectory/206#-:-LEu_VODE5mmW2jOPC3s:bnfp4nl)*

**Comment by johlju** [comment]
@thequietman44 Great work on this one! Thank you! 😃

**Pull request merged**
